In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_excel('smartphones.xlsx')
df.to_csv('output.csv',index=False, encoding="utf-8")

In [4]:
df=pd.read_csv('output.csv')
df.head()

,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,OnePlus 11 5G,"₹54,999",89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,OnePlus Nord CE 2 Lite 5G,"₹19,989",81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,Samsung Galaxy A14 5G,"₹16,499",75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,Motorola Moto G62 5G,"₹14,999",81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,Realme 10 Pro Plus,"₹24,999",82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

## Quality related issues ##

- model - consistency issues in the name `consistency`
- price - must be int by removing , and rs symbol , some phone has price as 99 `validity`
- rating - missing values in column `completion`
- sim - many things stacked into single column `tidyness`
- processor - the rows have something else info `validity`
- row 756 has ipods which is not desirable `validity`
- ram - must be different for inbuilt and builtin and also remove gb and make it int `validity `
- battery - incorrect row values `accuracy`
- card - incorrect row values `validity`
- missing values in camera , card and operating system  `completion`
- datatype of price , rating and rs is incorrect `validity`
## tideness related issues (messy data) ##

- sim - can be split into multiple useful values 
- processor - can be split
- battery - can be split 
- display - same as above 
- camera - same as above

In [5]:
df.info()
copy=df.copy()
print(f'\n the duplicated rows are {int(df.duplicated().sum())}')
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   model      1020 non-null   str
 1   price      1020 non-null   str
 2   rating     879 non-null    float64
 3   sim        1020 non-null   str
 4   processor  1020 non-null   str
 5   ram        1020 non-null   str
 6   battery    1020 non-null   str
 7   display    1020 non-null   str
 8   camera     1019 non-null   str
 9   card       1013 non-null   str
 10  os         1003 non-null   str
dtypes: float64(1), str(10)
memory usage: 87.8 KB

 the duplicated rows are 0

           rating
count  879.000000
mean    78.258248
std      7.402854
min     60.000000
25%     74.000000
50%     80.000000
75%     84.000000
max     89.000000

In [6]:
df['price'] = df['price'].replace({"₹": "", ",": ""}, regex=True)
df['price']=df['price'].astype('int')

In [13]:
df=df.reset_index()

In [16]:
battery_rows = set((113,151,309,365,378,441,450,553,584,610,613,630,642,647,649,659,667,701,750,756,759,764,819,855,859,884,915,916,927,929,932,990,1002))
camera_rows = set((100,113,151,157,161,238,273,308,309,323,324,365,367,378,394,441,450,484,506,534,553,571,572,575,584,610,613,615,630,642,647,649,659,667,684,687,705,711,723,728,750,756,759,764,792,819,846,854,855,858,883,884,896,915,916,927,929,932,945,956,990,995,1002,1016))
processor_rows = set((642,647,649,659,667,701,750,759,819,859,883,884,919,927,929,932,1002))
ram_rows = set((441,485,534,553,584,610,613,642,647,649,659,667,701,750,759,819,859,884,919,927,929,932,990,1002))
display_rows = set((378,441,450,553,584,610,613,630,642,647,649,659,667,701,750,759,764,819,859,884,915,916,927,929,932,990,1002))

df[df['index'].isin(battery_rows & camera_rows & processor_rows & ram_rows & display_rows)].describe()

             index        price  rating
count    13.000000    13.000000     0.0
mean    789.692308  2537.692308     NaN
std     132.274578  1464.718197     NaN
min     642.000000   958.000000     NaN
25%     659.000000  1339.000000     NaN
50%     759.000000  2099.000000     NaN
75%     927.000000  3290.000000     NaN
max    1002.000000  5490.000000     NaN

In [14]:
df['index']=df['index']+2

In [15]:
df.head()

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,2,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,3,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,4,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,5,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,6,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

In [17]:
df=df[df['price']>=3400] #through observations found out that the price above 3400 are not smartphones

In [18]:
df=df[~df['index'].isin(processor_rows)]

In [19]:
df[df['index'].isin(ram_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15,No FM Radio
483,485,Huawei Mate 50 RS Porsche Design,239999,81.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor",512 GB inbuilt,4700 mAh Battery with 66W Fast Charging,"6.74 inches, 1212 x 2616 px, 120 Hz Display",50 MP + 48 MP + 13 MP Triple Rear & 13 MP Fron...,"Memory Card (Hybrid), upto 256 GB",Hongmeng OS v3.0
582,584,Nokia 8210 4G,3749,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.8 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB"

In [20]:
df.drop(582,inplace=True)

In [21]:
df[df['index'].isin(ram_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15,No FM Radio
483,485,Huawei Mate 50 RS Porsche Design,239999,81.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor",512 GB inbuilt,4700 mAh Battery with 66W Fast Charging,"6.74 inches, 1212 x 2616 px, 120 Hz Display",50 MP + 48 MP + 13 MP Triple Rear & 13 MP Fron...,"Memory Card (Hybrid), upto 256 GB",Hongmeng OS v3.0

In [22]:
df[df['index'].isin(battery_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
307,309,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
363,365,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
376,378,Nokia 2660 Flip,4649,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.8 inches, 240 x 320 px Display",Dual Display,0.3 MP Rear Camera
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15,No FM Radio
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt","6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15,No FM Radio
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0,No FM Radio
754,756,Apple iPod Touch (7th Gen),18900,NaN,Wi-Fi,32 GB inbuilt,"4 inches, 640 x 1136 px Display",8 MP Rear & 1.2 MP Front Camera,iOS v12,No FM Radio,Bluetooth,Browser
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16,No FM Radio
853,855,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0,No FM Radio
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio

In [23]:
df.drop([376,754],inplace=True)

In [24]:
temp=df[df['index'].isin(battery_rows)]
temp=temp.iloc[:,7:].shift(1,axis=1)
df.loc[temp.index,temp.columns]=temp

In [25]:
temp

,battery,display,camera,card,os
111,NaN,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
149,NaN,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
307,NaN,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
363,NaN,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
439,NaN,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15
448,NaN,"6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15
628,NaN,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
762,NaN,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16
853,NaN,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
913,NaN,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
914,NaN,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14

In [26]:
df[df['index'].isin(battery_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",NaN,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",NaN,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
307,309,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",NaN,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
363,365,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",NaN,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,NaN,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt",NaN,"6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt",NaN,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,NaN,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16
853,855,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt",NaN,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",NaN,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",NaN,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14

In [27]:
df[df['index'].isin(display_rows)]['display']

439                    4.7 inches, 750 x 1334 px Display
448    6.06 inches, 1170 x 2532 px, 120 Hz Display wi...
628    6.1 inches, 1170 x 2532 px Display with Large ...
762                    6.1 inches, 750 x 1580 px Display
913                   5.4 inches, 1080 x 2340 px Display
914    6.1 inches, 1170 x 2532 px Display with Large ...
Name: display, dtype: str

In [28]:
tempdf=df[df['index'].isin(camera_rows)]

In [29]:
tempdf.head()
tempdf=tempdf[
    ~tempdf['camera'].str.contains('MP') &
    tempdf['os'].str.contains('Memory')
]
tempdf.loc[:, ['camera','card','os']] = tempdf.loc[:, ['camera','card','os']].shift(-1, axis=1)
tempdf

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
155,157,Nokia 2780 Flip,4990,NaN,"Dual Sim, 3G, 4G, Wi-Fi","Snapdragon QM215, Quad Core, 1.3 GHz Processor","4 GB RAM, 512 MB inbuilt",1450 mAh Battery,"2.7 inches, 240 x 320 px Display",5 MP Rear Camera,"Memory Card Supported, upto 32 GB",NaN
159,161,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4520 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported,NaN
271,273,Nokia 2720 V Flip,6199,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 205 , Dual Core, 1.1 GHz Processor","512 MB RAM, 4 GB inbuilt",1500 mAh Battery,"2.8 inches, 240 x 320 px Display",2 MP Rear Camera,Memory Card Supported,NaN
306,308,Samsung Galaxy Z Flip 3,69999,84.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,NaN
322,324,Royole FlexPai 2,109999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",4450 mAh Battery,"7.8 inches, 1440 x 1920 px Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB",NaN
365,367,OPPO Find N Flip,89990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","8 GB RAM, 128 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1200 x 2400 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,NaN
392,394,OPPO Find N2 Flip,70990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,NaN
504,506,Samsung Galaxy Z Flip 4 5G,89999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,NaN
570,572,LG Wing 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 765G , Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display",64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,"Memory Card (Hybrid), upto 2 TB",NaN
613,615,Oukitel WP21,22990,82.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G99, Octa Core, 2.2 GHz Processor","12 GB RAM, 256 GB inbuilt",9800 mAh Battery with 66W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display",64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,Memory Card (Hybrid),NaN
682,684,LG V60 ThinQ,79990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display with Punch ...",64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,"Memory Card (Hybrid), upto 2 TB",NaN
721,723,Asus ROG Phone 6D Ultimate,107990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 65W Fast Charging,"6.78 inches, 1080 x 2448 px, 165 Hz Display",50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,Memory Card Not Supported,NaN
726,728,Huawei Mate Xs 2,162990,89.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"7.8 inches, 2200 x 2480 px, 120 Hz Display wit...",50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,"Memory Card (Hybrid), upto 256 GB",NaN
844,846,CAT S22 Flip,14999,NaN,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Qualcomm 215, Quad Core, 1.3 GHz Processor","2 GB RAM, 16 GB inbuilt",2000 mAh Battery,"4 inches, 480 x 640 px Display",5 MP Rear & 2 MP Front Camera,"Memory Card Supported, upto 128 GB",NaN
894,896,Royole FlexPai 3 5G,149999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3360 mAh Battery,"7.2 inches, 1440 x 1920 px Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB",NaN
993,995,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Kirin 990, Octa Core, 2.86 GHz Processor","8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,"8 inches, 2200 x 2480 px Display",48 MP Quad Rear Camera,"Memory Card (Hybrid), upto 256 GB",NaN

In [30]:
df.loc[tempdf.index,tempdf.columns]=tempdf

In [31]:
df[df['index'].isin(camera_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
98,100,Vivo X Fold 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",NaN,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",NaN,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
155,157,Nokia 2780 Flip,4990,NaN,"Dual Sim, 3G, 4G, Wi-Fi","Snapdragon QM215, Quad Core, 1.3 GHz Processor","4 GB RAM, 512 MB inbuilt",1450 mAh Battery,"2.7 inches, 240 x 320 px Display",5 MP Rear Camera,"Memory Card Supported, upto 32 GB",NaN
159,161,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4520 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported,NaN
236,238,Xiaomi Mix Fold 2 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8+ Gen1 , Octa Core, 3.2 GHz Proce...","12 GB RAM, 256 GB inbuilt",4500 mAh Battery with 67W Fast Charging,"8.02 inches, 1914 x 2160 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...,Android v12
271,273,Nokia 2720 V Flip,6199,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 205 , Dual Core, 1.1 GHz Processor","512 MB RAM, 4 GB inbuilt",1500 mAh Battery,"2.8 inches, 240 x 320 px Display",2 MP Rear Camera,Memory Card Supported,NaN
306,308,Samsung Galaxy Z Flip 3,69999,84.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,NaN
307,309,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",NaN,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
321,323,Samsung Galaxy Z Fold 4,154998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
322,324,Royole FlexPai 2,109999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",4450 mAh Battery,"7.8 inches, 1440 x 1920 px Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB",NaN
363,365,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",NaN,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
365,367,OPPO Find N Flip,89990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","8 GB RAM, 128 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1200 x 2400 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,NaN
392,394,OPPO Find N2 Flip,70990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,NaN
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,NaN,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt",NaN,"6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15
482,484,Vivo X Fold Plus,113990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4730 mAh Battery with 80W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera,Android v12
504,506,Samsung Galaxy Z Flip 4 5G,89999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,NaN
569,571,Samsung Galaxy Z Fold 3,110999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1768 x 2208 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...,Android v11
570,572,LG Wing 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 765G , Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display",64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,"Memory Card (Hybrid), upto 2 TB",NaN
613,615,Oukitel WP21,22990,82.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G99, Octa Core, 2.2 GHz Processor","12 GB RAM, 256 GB inbuilt",9800 mAh Battery with 66W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display",64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,Memory Card (Hybrid),NaN
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt",NaN,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
682,684,LG V60 ThinQ,79990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display with Punch ...",64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,"Memory Card (Hybrid), upto 2 TB",NaN
703,705,Oppo Find N 5G,92249,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...,Android v11
709,711,OPPO X 2021,134999,86.0,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"7.4 inches, 1440 x 3200 px Display",Dual Display,64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...,Android v11
721,723,Asus ROG Phone 6D Ultimate,107990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 65W Fast Charging,"6.78 inches, 1080 x 2448 px, 165 Hz Display",50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,Memory Card Not Supported,NaN
726,728,Huawei Mate Xs 2,162990,89.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"7.8 inches, 2200 x 2480 px, 120 Hz Display wit...",50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,"Memory Card (Hybrid), upto 256 GB",NaN
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,NaN,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16
790,792,Xiaomi Mi Mix Fold,109990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 888 , Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",5020 mAh Battery with 67W Fast Charging,"8.01 inches, 1860 x 2480 px, 90 Hz Display","Foldable Display, Dual Display",108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...,Android v10
844,846,CAT S22 Flip,14999,NaN,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Qualcomm 215, Quad Core, 1.3 GHz Processor","2 GB RAM, 16 GB inbuilt",2000 mAh Battery,"4 inches, 480 x 640 px Display",5 MP Rear & 2 MP Front Camera,"Memory Card Supported, upto 128 GB",NaN
853,855,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt",NaN,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
856,858,Samsung Galaxy A01 Core,4999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","(28 nm), Quad Core, 1.5 GHz Processor","1 GB RAM, 16 GB inbuilt",3000 mAh Battery,"5.3 inches, 720 x 1480 px Display",8 MP Rear & 5 MP Front Camera,Memory Card Supported,Android v10
894,896,Royole FlexPai 3 5G,149999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3360 mAh Battery,"7.2 inches, 1440 x 1920 px Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB",NaN
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",NaN,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",NaN,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
943,945,Samsung Galaxy Z Fold 4 (12GB RAM + 1TB),163980,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 1 TB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
954,956,Vivo X Fold 5G (12GB RAM + 512GB),118990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
993,995,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Kirin 990, Octa Core, 2.86 GHz Processor","8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,"8 inches, 2200 x 2480 px Display",48 MP Quad Rear Camera,"Memory Card (Hybrid), upto 256 GB",NaN
1014,1016,Vivo X Fold 2,119990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,Android v12

In [32]:
df['camera'].value_counts()

camera
50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front Camera                  40
64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front Camera                  38
50 MP + 2 MP + 2 MP Triple Rear & 16 MP Front Camera                  34
13 MP + 2 MP Dual Rear & 5 MP Front Camera                            23
12 MP + 12 MP Dual Rear & 12 MP Front Camera                          20
                                                                      ..
50 MP + 13 MP + 2 MP Triple Rear & 32 MP + 16 MP Dual Front Camera     1
64 MP + 20 MP + 2 MP Triple Rear & 32 MP + 32 MP Dual Front Camera     1
50 MP + 48 MP + 32 MP Triple Rear & 32 MP Front Camera                 1
50 MP + 50 MP + 50 MP Triple Rear & 12 MP Front Camera                 1
48 MP + 2 MP + Depth Sensor Triple Rear & 8 MP Front Camera            1
Name: count, Length: 280, dtype: int64

In [33]:
pd.set_option('display.max_rows',None)

In [34]:
temp=df[df['camera'].str.contains('Display')]
temp

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
69,71,Oppo Find N Fold,99990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",64 MP + 10 MP + 8 MP Triple Rear & 32 MP Front...,Android v12
98,100,Vivo X Fold 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
236,238,Xiaomi Mix Fold 2 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8+ Gen1 , Octa Core, 3.2 GHz Proce...","12 GB RAM, 256 GB inbuilt",4500 mAh Battery with 67W Fast Charging,"8.02 inches, 1914 x 2160 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...,Android v12
321,323,Samsung Galaxy Z Fold 4,154998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
482,484,Vivo X Fold Plus,113990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4730 mAh Battery with 80W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera,Android v12
569,571,Samsung Galaxy Z Fold 3,110999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1768 x 2208 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...,Android v11
703,705,Oppo Find N 5G,92249,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...,Android v11
709,711,OPPO X 2021,134999,86.0,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"7.4 inches, 1440 x 3200 px Display",Dual Display,64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...,Android v11
790,792,Xiaomi Mi Mix Fold,109990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 888 , Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",5020 mAh Battery with 67W Fast Charging,"8.01 inches, 1860 x 2480 px, 90 Hz Display","Foldable Display, Dual Display",108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...,Android v10
943,945,Samsung Galaxy Z Fold 4 (12GB RAM + 1TB),163980,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 1 TB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
954,956,Vivo X Fold 5G (12GB RAM + 512GB),118990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
1014,1016,Vivo X Fold 2,119990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,Android v12

In [35]:
df.loc[temp.index,'camera']=temp.loc[:,'card']
df.loc[temp.index,'camera']

69      64 MP + 10 MP + 8 MP Triple Rear & 32 MP Front...
98                   50 MP Quad Rear & 16 MP Front Camera
236     50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...
321     50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...
482     50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera
569     12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...
703     50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...
709     64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...
790     108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...
943     50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...
954                  50 MP Quad Rear & 16 MP Front Camera
1014    50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...
Name: camera, dtype: str

In [36]:
df.loc[temp.index,'card']='Memory Card Not Supported'

In [37]:
df.loc[temp.index,'camera']

69      64 MP + 10 MP + 8 MP Triple Rear & 32 MP Front...
98                   50 MP Quad Rear & 16 MP Front Camera
236     50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...
321     50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...
482     50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera
569     12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...
703     50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...
709     64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...
790     108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...
943     50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...
954                  50 MP Quad Rear & 16 MP Front Camera
1014    50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...
Name: camera, dtype: str

In [38]:
df['card'].value_counts(
)

card
Memory Card Supported, upto 1 TB       171
Memory Card Not Supported              141
Android v12                            107
Memory Card Supported, upto 512 GB     105
Memory Card (Hybrid), upto 1 TB         91
Memory Card Supported                   90
Memory Card Supported, upto 256 GB      89
Android v13                             46
Android v11                             41
Memory Card (Hybrid)                    31
Memory Card (Hybrid), upto 256 GB       15
Memory Card (Hybrid), upto 512 GB       11
Android v10                             11
Memory Card Supported, upto 128 GB       7
Memory Card Supported, upto 2 TB         5
Memory Card Supported, upto 32 GB        5
Memory Card (Hybrid), upto 128 GB        3
Memory Card (Hybrid), upto 64 GB         3
Memory Card (Hybrid), upto 2 TB          3
Android v9.0 (Pie)                       2
Android v12.1                            1
Memory Card Supported, upto 1000 GB      1
iOS v10                                  1
Android v10.0                            1
iOS v13                                  1
HarmonyOS v2.0                           1
HarmonyOS                                1
Name: count, dtype: int64

In [40]:
df[~df['card'].str.contains('Memory')]
df.head()

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,2,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,3,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,4,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,5,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,6,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

In [41]:
temp=df[df['card'].str.contains('Android')]
temp

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
8,10,Nothing Phone 1,26749,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 778G Plus, Octa Core, 2.5 GHz Proce...","8 GB RAM, 128 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 50 MP Dual Rear & 16 MP Front Camera,Android v12,No FM Radio
9,11,OnePlus Nord 2T 5G,28999,84.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 1300, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",4500 mAh Battery with 80W Fast Charging,"6.43 inches, 1080 x 2400 px, 90 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 32 MP Front ...,Android v12,No FM Radio
12,14,Xiaomi Redmi Note 12 Pro 5G,24762,79.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
17,19,OPPO Reno 9 Pro Plus,45999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","16 GB RAM, 256 GB inbuilt",4700 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 32 MP Front ...,Android v13,No FM Radio
18,20,OnePlus 10R 5G,32999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 8100 Max, Octa Core, 2.85 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,Bluetooth
20,22,OnePlus 11R,39999,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 12 MP + 2 MP Triple Rear & 16 MP Front...,Android v13,Bluetooth
21,23,Vivo V25 Pro 5G,35999,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1300, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",4830 mAh Battery with 66W Fast Charging,"6.56 inches, 1080 x 2376 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 32 MP Front ...,Android v12,No FM Radio
24,26,Vivo V26 Pro,42990,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 100W Fast Charging,"6.7 inches, 1080 x 2400 px, 120 Hz Display wit...",64 MP + 8 MP + 2 MP Triple Rear & 32 MP Front ...,Android v13,No FM Radio
29,31,OnePlus 11 Pro,69999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4500 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Android v13,No FM Radio
37,39,Samsung Galaxy S22 Ultra 5G,91999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.8 inches, 1440 x 3080 px, 120 Hz Display wit...",108 MP Quad Rear & 40 MP Front Camera,Android v12,Bluetooth
39,41,OPPO Reno 9 5G,28499,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 778G, Octa Core, 2.4 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",64 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v13,No FM Radio
51,53,iQOO Neo 7 5G,29999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8200, Octa Core, 3.1 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 120W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,Android v13,No FM Radio
58,60,Samsung Galaxy S23 Plus,84990,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4700 mAh Battery with 45W Fast Charging,"6.6 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 12 MP Fron...,Android v13,No FM Radio
60,62,Xiaomi Redmi Note 13 Pro 5G,17990,78.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 720, Octa Core, 2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.67 inches, 1080 x 2460 px, 120 Hz Display wi...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Android v12,Bluetooth
61,63,Vivo S16,29990,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 870, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 50 MP Front ...,Android v13,No FM Radio
65,67,Vivo S16 Pro,35499,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 8200, Octa Core, 3.1 GHz Processor","8 GB RAM, 256 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 50 MP Front ...,Android v13,No FM Radio
66,68,OnePlus 10 Pro 5G,60999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 80W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 8 MP Triple Rear & 32 MP Front...,Android v12,No FM Radio
73,75,OnePlus 10T,44999,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4800 mAh Battery with 150W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
85,87,Motorola Edge 30 5G,22999,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 778G+, Octa Core, 2.5 GHz Processor","6 GB RAM, 128 GB inbuilt",4020 mAh Battery with 33W Fast Charging,"6.5 inches, 1080 x 2400 px, 144 Hz Display wit...",50 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Android v12,No FM Radio
91,93,OnePlus Ace Racing Edition 5G,22990,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 8100 Max, Octa Core, 2.85 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
93,95,Vivo X90 Pro Plus 5G,73999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4700 mAh Battery with 80W Fast Charging,"6.78 inches, 1440 x 3200 px, 120 Hz Display wi...",50.3 MP Quad Rear & 32 MP Front Camera,Android v13,No FM Radio
97,99,iQOO 11 5G,59999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",5000 mAh Battery with 120W Fast Charging,"6.78 inches, 1440 x 3200 px, 144 Hz Display wi...",50 MP + 13 MP + 8 MP Triple Rear & 16 MP Front...,Android v13,No FM Radio
102,104,Motorola Moto S30 Pro,23990,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 888+, Octa Core, 2.9 GHz Processor","8 GB RAM, 128 GB inbuilt",4400 mAh Battery with 68W Fast Charging,"6.55 inches, 1080 x 2460 px, 144 Hz Display wi...",50 MP + 13 MP + 2 MP Triple Rear & 32 MP Front...,Android v12,No FM Radio
106,108,Vivo V27 Pro,43999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 120W Fast Charging,"6.73 inches, 1080 x 2400 px, 144 Hz Display wi...",108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front...,Android v13,No FM Radio
107,109,Samsung Galaxy S22 5G,49999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.1 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP Fron...,Android v12,Bluetooth
109,111,OnePlus 10R 5G (12GB RAM + 256GB),36999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 8100 Max, Octa Core, 2.85 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,Bluetooth
110,112,Tecno Phantom X2,39999,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","8 GB RAM, 256 GB inbuilt",5160 mAh Battery with 45W Fast Charging,"6.8 inches, 1080 x 2400 px, 120 Hz Display wit...",64 MP + 13 MP + 2 MP Triple Rear & 32 MP Front...,Android v12,No FM Radio
112,114,Xiaomi Redmi K50i 5G,22999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 8100, Octa Core, 2.85 GHz Processor","6 GB RAM, 128 GB inbuilt",5080 mAh Battery with 67W Fast Charging,"6.6 inches, 1080 x 2460 px, 144 Hz Display wit...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,Bluetooth
115,117,OPPO Reno8 5G,29340,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 1300, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",4500 mAh Battery with 80W Fast Charging,"6.43 inches, 1080 x 2400 px, 90 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 32 MP Front ...,Android v12,No FM Radio
119,121,Samsung Galaxy S23,70990,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3900 mAh Battery with 25W Fast Charging,"6.1 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 12 MP Fron...,Android v13,No FM Radio
120,122,Motorola Edge 30 Pro 5G,34999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",4800 mAh Battery with 68W Fast Charging,"6.7 inches, 1080 x 2400 px, 144 Hz Display wit...",50 MP + 50 MP + 2 MP Triple Rear & 60 MP Front...,Android v12,No FM Radio
121,123,OnePlus Nord 2T (12GB RAM + 256GB),33900,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 1300, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",4500 mAh Battery with 80W Fast Charging,"6.43 inches, 1080 x 2400 px, 90 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 32 MP Front ...,Android v12,No FM Radio
133,135,Nothing Phone 1 (8GB RAM + 256GB),28249,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 778G Plus, Octa Core, 2.5 GHz Proce...","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 50 MP Dual Rear & 16 MP Front Camera,Android v12,No FM Radio
139,141,iQOO Neo 6 5G,28999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Snapdragon 870, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4700 mAh Battery with 80W Fast Charging,"6.62 inches, 1080 x 2400 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
141,143,OPPO Reno 9 Pro 5G,39999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 8100 Max, Octa Core, 2.85 GHz Processor","16 GB RAM, 256 GB inbuilt",4500 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Android v13,No FM Radio
146,148,iQOO 7,24990,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 870, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4400 mAh Battery with 66W Fast Charging,"6.62 inches, 1080 x 2400 px, 120 Hz Display wi...",48 MP + 13 MP + 2 MP Triple Rear & 16 MP Front...,Android v11,No FM Radio
163,165,Oppo Reno 10 Pro Plus,58990,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4700 mAh Battery with 80W Fast Charging,"6.73 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP Quad Rear & 32 MP Front Camera,Android v13,No FM Radio
168,170,iQOO 9 SE 5G,30990,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888 , Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",4500 mAh Battery with 66W Fast Charging,"6.62 inches, 1080 x 2400 px, 120 Hz Display wi...",48 MP + 13 MP + 2 MP Triple Rear & 16 MP Front...,Android v12,No FM Radio
170,172,Letv Y1 Pro,5499,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Tiger T310, Quad Core, 2 GHz Processor","4 GB RAM, 32 GB inbuilt",4000 mAh Battery,"6.54 inches, 720 x 1560 px Display with Small ...",8 MP + Depth Sensor Dual Rear & 5 MP Front Camera,Android v11,No FM Radio
183,185,Motorola Moto X40,39999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4600 mAh Battery with 125W Fast Charging,"6.7 inches, 1080 x 2400 px, 165 Hz Display",50 MP + 50 MP + 12 MP Triple Rear & 60 MP Fron...,Android v13,No FM Radio
186,188,OnePlus Nord 3 5G,27999,84.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 8200, Octa Core, 3.1 GHz Processor","8 GB RAM, 128 GB inbuilt",4200 mAh Battery with 120W Fast Charging,"6.43 inches, 1080 x 2400 px, 90 Hz Display wit...",50 MP + 12 MP + 5 MP Triple Rear & 32 MP Front...,Android v11,No FM Radio
189,191,LeEco S1 Pro,10999,65.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Tiger T7150, Quad Core, 1.8 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 10W Fast Charging,"6.5 inches, 720 x 1600 px Display with Small N...",13 MP + Depth Sensor Dual Rear & 5 MP Front Ca...,Android v11,No FM Radio
196,198,OPPO Reno 8 Pro House of Dragon Edition,45999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 8100-Max, Octa Core, 2.85 GHz Processor","12 GB RAM, 256 GB inbuilt",4500 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 32 MP Front ...,Android v12,No FM Radio
202,204,Motorola Edge 30 Ultra,54999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4610 mAh Battery with 125W Fast Charging,"6.67 inches, 1080 x 2400 px, 144 Hz Display wi...",200 MP + 50 MP + 12 MP Triple Rear & 60 MP Fro...,Android v12,No FM Radio
203,205,Xiaomi 13 Ultra 5G,71999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 120W Fast Charging,"6.6 inches, 1440 x 3200 px, 120 Hz Display wit...",108 MP Quad Rear & 32 MP Front Camera,Android v12,No FM Radio
206,208,Nothing Phone 1 (12GB RAM + 256GB),35999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 778G Plus, Octa Core, 2.5 GHz Proce...","12 GB RAM, 256 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 50 MP Dual Rear & 16 MP Front Camera,Android v12,No FM Radio
209,211,Xiaomi Redmi Note 12 Pro (8GB RAM + 256GB),27994,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 1080, Octa Core, 2.6 GHz Processor","8 GB RAM, 256 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
211,213,Vivo V25 Pro (12GB RAM + 256GB),39999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1300, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",4830 mAh Battery with 66W Fast Charging,"6.56 inches, 1080 x 2376 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 32 MP Front ...,Android v12,No FM Radio
215,217,Honor X9a,27999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 695, Octa Core, 2.2 GHz Processor","8 GB RAM, 256 GB inbuilt",5100 mAh Battery with 40W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",64 MP + 5 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
216,218,Google Pixel 7 Pro 5G,81999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Google Tensor G2, Octa Core, 2.85 GHz Processor","12 GB RAM, 128 GB inbuilt",5000 mAh Battery with 30W Fast Charging,"6.7 inches, 1440 x 3120 px, 120 Hz Display wit...",50 MP + 48 MP + 12 MP Triple Rear & 10.8 MP Fr...,Android v13,No FM Radio
220,222,Xiaomi Redmi K60,29990,84.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",5500 mAh Battery with 67W Fast Charging,"6.67 inches, 1440 x 3200 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v13,No FM Radio
223,225,Motorola Edge 30 5G (8GB RAM + 128GB),24999,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 778G+, Octa Core, 2.5 GHz Processor","8 GB RAM, 128 GB inbuilt",4020 mAh Battery with 33W Fast Charging,"6.5 inches, 1080 x 2400 px, 144 Hz Display wit...",50 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Android v12,No FM Radio
228,230,Realme GT Neo 3T,24999,79.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 870, Octa Core, 3.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 80W Fast Charging,"6.62 inches, 1080 x 2400 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
229,231,OPPO Reno 8 Pro 5G,45999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 8100-Max, Octa Core, 2.85 GHz Processor","12 GB RAM, 256 GB inbuilt",4500 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 32 MP Front ...,Android v12,No FM Radio
230,232,OnePlus 10 Pro 5G (12GB RAM + 256GB),65499,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 80W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 8 MP Triple Rear & 32 MP Front...,Android v12,No FM Radio
231,233,iQOO 11 Pro 5G,58990,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4700 mAh Battery with 200W Fast Charging,"6.78 inches, 1440 x 3200 px, 144 Hz Display wi...",50 MP + 50 MP + 13 MP Triple Rear & 16 MP Fron...,Android v13,No FM Radio
244,246,Google Pixel 7 5G,53100,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Google Tensor G2, Octa Core, 2.85 GHz Processor","8 GB RAM, 128 GB inbuilt",4355 mAh Battery with 30W Fast Charging,"6.3 inches, 1080 x 2400 px, 90 Hz Display with...",50 MP + 12 MP Dual Rear & 10.8 MP Front Camera,Android v13,No FM Radio
249,251,Nubia Red Magic 8 Pro 5G,46990,84.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"6.8 inches, 1116 x 2480 px, 120 Hz Display",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v13,No FM Radio
251,253,Tecno Phantom X2 Pro,49999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","12 GB RAM, 256 GB inbuilt",5160 mAh Battery with 45W Fast Charging,"6.8 inches, 1080 x 2400 px, 120 Hz Display wit...",50 MP + 50 MP + 13 MP Triple Rear & 32 MP Fron...,Android v12,Bluetooth
257,259,Samsung Galaxy S22 Plus 5G,64449,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",4500 mAh Battery with 45W Fast Charging,"6.6 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP Fron...,Android v12,Bluetooth
258,260,Vivo U3x,8990,71.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 480 , Octa Core, 2 GHz Processor","6 GB RAM, 64 GB inbuilt",5000 mAh Battery with 18W Fast Charging,"6.58 inches, 1080 x 2408 px, 90 Hz Display wit...",13 MP + 2 MP Dual Rear & 8 MP Front Camera,Android v11,No FM Radio

In [42]:
df.loc[temp.index,'os']=temp.loc[:,'card']

In [43]:
df.loc[temp.index,'card']='Memory Card Not Supported'

In [44]:
temp=df[df['card'].str.contains('iOS')]

In [45]:
df.loc[temp.index,'os']=temp.loc[:,'card']
df.loc[temp.index,'card']='Memory Card Not Supported'

In [46]:
temp=df[~df['card'].str.contains('Memory')]
temp['card'].value_counts()

card
HarmonyOS v2.0    1
HarmonyOS         1
Name: count, dtype: int64

In [47]:
df.loc[temp.index,'camera']=temp.loc[:,'card']
df.loc[temp.index,'card']='Memory Card Not Supported'

In [48]:
df['card'].value_counts()

card
Memory Card Not Supported              354
Memory Card Supported, upto 1 TB       171
Memory Card Supported, upto 512 GB     105
Memory Card (Hybrid), upto 1 TB         91
Memory Card Supported                   90
Memory Card Supported, upto 256 GB      89
Memory Card (Hybrid)                    31
Memory Card (Hybrid), upto 256 GB       15
Memory Card (Hybrid), upto 512 GB       11
Memory Card Supported, upto 128 GB       7
Memory Card Supported, upto 2 TB         5
Memory Card Supported, upto 32 GB        5
Memory Card (Hybrid), upto 128 GB        3
Memory Card (Hybrid), upto 64 GB         3
Memory Card (Hybrid), upto 2 TB          3
Memory Card Supported, upto 1000 GB      1
Name: count, dtype: int64

In [49]:
df['os'].value_counts()

os
Android v12                        394
Android v11                        274
Android v13                         91
Android v10                         69
Android v9.0 (Pie)                  29
Android v10.0                       23
iOS v16                             15
iOS v15                             12
Android v8.1 (Oreo)                 10
iOS v14                              6
iOS v13                              4
Android v11.0                        4
Android v8.0 (Oreo)                  4
iOS v15.0                            3
Android v12.1                        2
Android v5.1.1 (Lollipop)            2
iOS v14.0                            2
Harmony v2.0                         2
No FM Radio                          2
Android v6.0 (Marshmallow)           2
EMUI v12                             2
HarmonyOS v2                         1
iOS v13.0                            1
iOS v12.3                            1
iOS v17                              1
Android v4.4.2 (KitKat)              1
Android v5.1 (Lollipop)              1
Hongmeng OS v3.0                     1
Bluetooth                            1
Pragati OS (Powered by Android)      1
iOS v10                              1
RTOS (Series 30+)                    1
Hongmeng OS v4.0                     1
HarmonyOS v2.0                       1
Android v7.1 (Nougat)                1
Android                              1
Android v9 (Pie)                     1
Name: count, dtype: int64

In [50]:
x=df[df['os'].str.contains('1.3 MP Rear Camera')].index
df.loc[x,'camera']=df.loc[x,'os']
df.loc[x,'os']=np.nan

In [51]:
df['os'].value_counts()

os
Android v12                        394
Android v11                        274
Android v13                         91
Android v10                         69
Android v9.0 (Pie)                  29
Android v10.0                       23
iOS v16                             15
iOS v15                             12
Android v8.1 (Oreo)                 10
iOS v14                              6
iOS v13                              4
Android v11.0                        4
Android v8.0 (Oreo)                  4
iOS v15.0                            3
Android v12.1                        2
Android v5.1.1 (Lollipop)            2
iOS v14.0                            2
Harmony v2.0                         2
No FM Radio                          2
Android v6.0 (Marshmallow)           2
EMUI v12                             2
HarmonyOS v2                         1
iOS v13.0                            1
iOS v12.3                            1
iOS v17                              1
Android v4.4.2 (KitKat)              1
Android v5.1 (Lollipop)              1
Hongmeng OS v3.0                     1
Bluetooth                            1
Pragati OS (Powered by Android)      1
iOS v10                              1
RTOS (Series 30+)                    1
Hongmeng OS v4.0                     1
HarmonyOS v2.0                       1
Android v7.1 (Nougat)                1
Android                              1
Android v9 (Pie)                     1
Name: count, dtype: int64

In [52]:
x=df[df['os'].str.contains('Memory Card')].index

In [53]:
df.loc[x,'os']=np.nan
df.loc[x].head()

Empty DataFrame
Columns: [index, model, price, rating, sim, processor, ram, battery, display, camera, card, os]
Index: []

In [54]:
df['os'].value_counts()

os
Android v12                        394
Android v11                        274
Android v13                         91
Android v10                         69
Android v9.0 (Pie)                  29
Android v10.0                       23
iOS v16                             15
iOS v15                             12
Android v8.1 (Oreo)                 10
iOS v14                              6
iOS v13                              4
Android v11.0                        4
Android v8.0 (Oreo)                  4
iOS v15.0                            3
Android v12.1                        2
Android v5.1.1 (Lollipop)            2
iOS v14.0                            2
Harmony v2.0                         2
No FM Radio                          2
Android v6.0 (Marshmallow)           2
EMUI v12                             2
HarmonyOS v2                         1
iOS v13.0                            1
iOS v12.3                            1
iOS v17                              1
Android v4.4.2 (KitKat)              1
Android v5.1 (Lollipop)              1
Hongmeng OS v3.0                     1
Bluetooth                            1
Pragati OS (Powered by Android)      1
iOS v10                              1
RTOS (Series 30+)                    1
Hongmeng OS v4.0                     1
HarmonyOS v2.0                       1
Android v7.1 (Nougat)                1
Android                              1
Android v9 (Pie)                     1
Name: count, dtype: int64

In [55]:
x=df[df['os'].str.contains('0.3 MP Rear Camera')].index
df.loc[x,'camera']=df.loc[x,'os']
df.loc[x,'os']=np.nan

In [56]:
x=df[df['os'].str.contains('Bluetooth')].index
df.loc[x,'os']=np.nan

In [57]:
x=df[df['os'].str.contains('Browser')].index
df.loc[x,'os']=np.nan

In [58]:

x=df[df['os'].str.contains('No FM Radio')].index
df.loc[x,'os']=np.nan

In [59]:
df['os'].value_counts()

os
Android v12                        394
Android v11                        274
Android v13                         91
Android v10                         69
Android v9.0 (Pie)                  29
Android v10.0                       23
iOS v16                             15
iOS v15                             12
Android v8.1 (Oreo)                 10
iOS v14                              6
iOS v13                              4
Android v11.0                        4
Android v8.0 (Oreo)                  4
iOS v15.0                            3
Android v12.1                        2
Android v5.1.1 (Lollipop)            2
iOS v14.0                            2
Harmony v2.0                         2
Android v6.0 (Marshmallow)           2
EMUI v12                             2
HarmonyOS v2                         1
iOS v13.0                            1
iOS v12.3                            1
iOS v17                              1
Android v4.4.2 (KitKat)              1
Android v5.1 (Lollipop)              1
Hongmeng OS v3.0                     1
Pragati OS (Powered by Android)      1
iOS v10                              1
RTOS (Series 30+)                    1
Hongmeng OS v4.0                     1
HarmonyOS v2.0                       1
Android v7.1 (Nougat)                1
Android                              1
Android v9 (Pie)                     1
Name: count, dtype: int64

In [60]:
df['processor'].value_counts()

processor
Dimensity 700 5G, Octa Core, 2.2 GHz Processor         29
Helio P35, Octa Core, 2.3 GHz Processor                27
Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor       26
Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor        23
Snapdragon 695, Octa Core, 2.2 GHz Processor           23
Snapdragon 680, Octa Core, 2.4 GHz Processor           23
Helio G35, Octa Core, 2.3 GHz Processor                20
Snapdragon  8 Gen1, Octa Core, 3 GHz Processor         18
Snapdragon  680, Octa Core, 2.4 GHz Processor          18
Snapdragon 8 Gen1, Octa Core, 3 GHz Processor          17
Snapdragon  695, Octa Core, 2.2 GHz Processor          16
Bionic A15, Hexa Core, 3.22 GHz Processor              16
Snapdragon 870, Octa Core, 3.2 GHz Processor           15
Dimensity  810 5G, Octa Core, 2.4 GHz Processor        15
Helio G99, Octa Core, 2.2 GHz Processor                14
Helio G80, Octa Core, 2 GHz Processor                  14
Dimensity 1080, Octa Core, 2.6 GHz Processor           12
Snapdragon  8+ Gen1, Octa Core, 3.2 GHz Processor      12
Snapdragon 778G, Octa Core, 2.4 GHz Processor          12
Dimensity 810 5G, Octa Core, 2.4 GHz Processor         12
Helio G96, Octa Core, 2.05 GHz Processor               12
Dimensity  920 5G, Octa Core, 2.5 GHz Processor        11
Snapdragon 888, Octa Core, 2.84 GHz Processor          11
Helio A22, Quad Core, 2 GHz Processor                  10
Snapdragon  888 , Octa Core, 2.84 GHz Processor        10
Helio  G85, Octa Core, 2 GHz Processor                 10
Helio G25, Octa Core, 2 GHz Processor                  10
Octa Core Processor                                     9
Tiger T612, Octa Core, 1.82 GHz Processor               9
Helio G37, Octa Core, 2.3 GHz Processor                 9
Dimensity 1300, Octa Core, 3 GHz Processor              8
Bionic A14, Hexa Core, 3.1 GHz Processor                8
Snapdragon 720G, Octa Core, 2.3 GHz Processor           8
Helio G88, Octa Core, 2 GHz Processor                   8
Snapdragon 865, Octa Core, 2.84 GHz Processor           7
Bionic  A16, Hexa Core Processor                        7
Helio G95, Octa Core, 2.05 GHz Processor                7
Snapdragon  870, Octa Core, 3.2 GHz Processor           7
Dimensity 8100 Max, Octa Core, 2.85 GHz Processor       6
Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor       6
Exynos 850, Octa Core, 2 GHz Processor                  6
Helio G85, Octa Core, 2 GHz Processor                   6
Helio  G96, Octa Core, 2.05 GHz Processor               6
Helio P22, Octa Core, 2 GHz Processor                   6
Snapdragon 778G Plus, Octa Core, 2.5 GHz Processor      5
Snapdragon 695 , Octa Core, 2.2 GHz Processor           5
A13 Bionic, Hexa Core, 2.65 GHz Processor               5
Exynos  2100, Octa Core, 2.9 GHz Processor              5
Snapdragon  7 Gen1, Octa Core, 2.36 GHz Processor       5
Dimensity 8200, Octa Core, 3.1 GHz Processor            5
Dimensity  8100, Octa Core, 2.85 GHz Processor          5
Snapdragon  778G, Octa Core, 2.4 GHz Processor          5
Snapdragon  695 , Octa Core, 2.2 GHz Processor          5
Dimensity 1200, Octa Core, 3 GHz Processor              5
Snapdragon  732G, Octa Core, 2.3 GHz Processor          5
Unisoc  SC9863A, Octa Core, 1.6 GHz Processor           5
Snapdragon 4 Gen 1, Octa Core, 2 GHz Processor          4
Dimensity 800U, Octa Core, 2.4 GHz Processor            4
Exynos  1280, Octa Core, 2.4 GHz Processor              4
Dimensity 720, Octa Core, 2 GHz Processor               4
Dimensity 9000, Octa Core, 3.05 GHz Processor           4
Snapdragon  480 , Octa Core, 2 GHz Processor            4
Snapdragon  778G , Octa Core, 2.4 GHz Processor         4
Dimensity 900, Octa Core, 2 GHz Processor               4
Exynos 990, Octa Core, 2.73 GHz Processor               4
Unisoc  T606, Octa Core, 1.6 GHz Processor              4
Exynos 1330, Octa Core, 2.4 GHz Processor               3
Dimensity  1300, Octa Core, 3 GHz Processor             3
Snapdragon  8 Gen2, Octa Core, 3.2 GHz Processor        3
Dimensity  930, Octa Core, 2.2 GHz Processor            3
 Snapdragon  695, Octa Core, 2.2 GHz Processor          3
Snapdragon 480+, Octa Core, 2.2 GHz Processor           3
Helio  G25, Octa Core, 2 GHz Processor                  3
Helio  G99, Octa Core, 2.2 GHz Processor                3
Dimensity 700, Octa Core, 2.2 GHz Processor             3
Snapdragon 888+, Octa Core, 2.9 GHz Processor           3
Exynos 1280, Octa Core, 2.4 GHz Processor               3
Tiger  T616, Octa Core, 1.8 GHz Processor               3
Bionic  A16                                             3
Dimensity 810, Octa Core, 2.4 GHz Processor             3
Helio G96, Octa Core, 2 GHz Processor                   3
Dimensity  700 5G, Octa Core, 2.2 GHz Processor         3
Dimensity 8100-Max, Octa Core, 2.85 GHz Processor       3
Octa Core, 2 GHz Processor                              3
Exynos  850, Octa Core, 2 GHz Processor                 3
Quad Core, 1.3 GHz Processor                            3
Qualcomm 215, Quad Core, 1.3 GHz Processor              3
Snapdragon  888+, Octa Core, 2.9 GHz Processor          3
Snapdragon 765G , Octa Core, 2.4 GHz Processor          3
Helio G95, Octa Core, 2 GHz Processor                   3
Snapdragon 845, Octa Core, 2.8 GHz Processor            3
Exynos  990, Octa Core, 2.73 GHz Processor              3
Snapdragon  865 , Octa Core, 2.84 GHz Processor         3
Snapdragon  665, Octa Core, 2 GHz Processor             3
Snapdragon 765G, Octa Core, 2.4 GHz Processor           3
Snapdragon  750G, Octa Core, 2.2 GHz Processor          2
Helio G70, Octa Core, 2 GHz Processor                   2
Dimensity  900, Octa Core, 2 GHz Processor              2
Dimensity  900 5G, Octa Core, 2.4 GHz Processor         2
Unisoc T612, Octa Core, 1.8 GHz Processor               2
Snapdragon 7 Gen1, Octa Core, 2.36 GHz Processor        2
Snapdragon  4 Gen 1, Octa Core, 2 GHz Processor         2
Dimensity 700 , Octa Core, 2.2 GHz Processor            2
Tiger  T310, Quad Core, 2 GHz Processor                 2
Snapdragon 6 Gen 1, Octa Core, 2.2 GHz Processor        2
Snapdragon 778G+, Octa Core, 2.5 GHz Processor          2
Dimensity 800U , Octa Core, 2.4 GHz Processor           2
Google  Tensor, Octa Core Processor                     2
Dimensity 9200, Octa Core, 3.05 GHz Processor           2
Dimensity 920 5G, Octa Core, 2.5 GHz Processor          2
Dimensity  8200, Octa Core, 3.1 GHz Processor           2
Quad Core, 1.6 GHz Processor                            2
Helio, Octa Core Processor                              2
Snapdragon 778G+, Octa Core Processor                   2
Snapdragon 712, Octa Core, 2.3 GHz Processor            2
Google  Tensor, Octa Core, 2.8 GHz Processor            2
SC9863A, Octa Core, 1.6 GHz Processor                   2
Snapdragon  480+, Octa Core, 2.2 GHz Processor          2
Snapdragon 732G , Octa Core, 2.3 GHz Processor          2
Unisoc SC9863A, Octa Core, 1.6 GHz Processor            2
Exynos 9820, Octa Core, 2.7 GHz Processor               2
Unisoc  T606, Octa Core, 2 GHz Processor                2
Snapdragon 662 , Octa Core, 2 GHz Processor             2
Snapdragon  778G Plus, Octa Core, 2.5 GHz Processor     2
Snapdragon 678, Octa Core, 2.2 GHz Processor            2
Bionic  A15, Hexa Core, 3.22 GHz Processor              2
Snapdragon  720G, Octa Core, 2.3 GHz Processor          2
Dimensity  9000, Octa Core, 3.05 GHz Processor          2
Helio G85 , Octa Core, 2 GHz Processor                  2
Snapdragon 855+, Octa Core, 2.96 GHz Processor          2
Snapdragon 865 , Octa Core, 2.84 GHz Processor          2
Helio G37, Octa Core, 1.8 GHz Processor                 2
Dimensity 8100, Octa Core, 2.85 GHz Processor           2
Helio P35 , Octa Core, 2.3 GHz Processor                2
Tiger T616, Octa Core, 2 GHz Processor                  2
Snapdragon  765G , Octa Core, 2.4 GHz Processor         2
Snapdragon 690, Octa Core, 2 GHz Processor              2
Unisoc  T610, Octa Core, 1.8 GHz Processor              2
Dimensity 700, Octa Core, 2 GHz Processor               2
Unisoc  SC9863a, Octa Core, 1.6 GHz Processor           2
Snapdragon  888, Octa Core, 2.84 GHz Processor          2
Exynos 9611, Octa Core, 2.3 GHz Processor               2
Helio P95, Octa Core, 2.2 GHz Processor                 2
Snapdragon  750G , Octa Core, 2.2 GHz Processor         2
Exynos 9825, Octa Core, 2.73 GHz Processor              2
Snapdragon  675, Octa Core, 2 GHz Processor             2
Snapdragon  439 , Octa Core, 2 GHz Processor            2
Snapdragon 439, Octa Core, 2 GHz Processor              2
Helio P60, Octa Core, 2 GHz Processor                   2
Snapdragon 460, Octa Core, 1.8 GHz Processor            2
Kirin  990, Octa Core, 2.86 GHz Processor               2
Exynos 1280, Octa Core Processor                        1
Tiger T700, Octa Core, 1.8 GHz Processor                1
Quad Core, 1.4 GHz Processor                            1
Snapdragon 460 , Octa Core, 1.8 GHz Processor           1
Exynos 1200, Octa Core, 2.4 GHz Processor               1
Snapdragon QM215, Quad Core, 1.3 GHz Processor          1
 Snapdragon 695, Octa Core, 2.2 GHz Processor           1
Tiger T310, Quad Core, 2 GHz Processor                  1
Tiger T7150, Quad Core, 1.8 GHz Processor               1
Helio  P22 , Octa Core, 2 GHz Processor                 1
Exynos 1380, Octa Core Processor                        1
Google  Tensor G2, Octa Core, 2.85 GHz Processor        1
Snapdragon  8+ Gen1 , Octa Core, 3.2 GHz Processor      1
Google Tensor G2, Octa Core, 2.85 GHz Processor         1
Dimensity 930, Octa Core, 2.2 GHz Processor             1
Exynos  2300, Octa Core Processor                       1
Dimensity 900, Octa Core, 2.4 GHz Processor             1
Apple  A13                                              1
Dimensity  1200 Max, Octa Core, 3 GHz Processor         1
Snapdragon 205 , Dual Core, 1.1 GHz Processor           1
Bionic A16                                              1
Dimensity  900, Octa Core, 2.4 GHz Processor            1
Google Tensor, Octa Core, 2.8 GHz Processor             1
Unisoc  SC9836A, Quad Core, 1.6 GHz Processor           1
Helio  G37, Octa Core, 2.3 GHz Processor                1
Snapdragon 8+ Gen 2, Octa Core Processor                1
Snapdragon 855, Octa Core, 2.8 GHz Processor            1
Snapdragon 730, Octa Core, 2.2 GHz Processor            1
Unisoc, Octa Core Processor                             1
Spreadtrum  SC7731E, Quad Core, 1.3 GHz Processor       1
Bionic  A17, Octa Core Processor                        1
Snapdragon  810, Octa Core, 2.4 GHz Processor           1
Snapdragon 775                                          1
Snapdragon 801, Octa Core, 1.5 GHz Processor            1
Snapdragon 860, Octa Core, 2.96 GHz Processor           1
Helio  P35, Octa Core, 2.3 GHz Processor                1
Unisoc T606, Octa Core, 1.6 GHz Processor               1
Tiger T610, Octa Core, 1.82 GHz Processor               1
Helio  G95, Octa Core, 2.05 GHz Processor               1
Helio MT6580, Quad Core, 1.3 GHz Processor              1
Snapdragon 615, Octa Core, 1.5 GHz Processor            1
Tiger T606, Octa Core, 2 GHz Processor                  1
Unisoc  SC9832E, Quad Core, 1.4 GHz Processor           1
Snapdragon  210, Quad Core, 1.1 GHz Processor           1
Sanpdragon 680, Octa Core, 2.4 GHz Processor            1
Snapdragon 835, Octa Core, 2.35 GHz Processor           1
Snapdragon  680 , Octa Core, 2.4 GHz Processor          1
Snapdragon 888+ , Octa Core, 2.9 GHz Processor          1
Snapdragon  720G , Octa Core, 2.3 GHz Processor         1
Snapdragon 425, Quad Core, 1.4 GHz Processor            1
Snapdragon 720G , Octa Core, 2.3 GHz Processor          1
Fusion APL1024, Quad Core, 2.37 GHz Processor           1
Unisoc T610, Octa Core, 1.8 GHz Processor               1
Unisoc T117                                             1
Snapdragon 732G, Octa Core, 2.3 GHz Processor           1
Kirin  9000, Octa Core, 3.13 GHz Processor              1
Tiger T610, Quad Core, 1.8 GHz Processor                1
Dimensity  9200, Octa Core Processor                    1
Snapdragon  6 Gen 1, Octa Core, 2.2 GHz Processor       1
Tiger  T610, Octa Core, 1.8 GHz Processor               1
Dimensity 1100 5G, Octa Core, 2.6 GHz Processor         1
Snapdragon  765G, Octa Core, 2.4 GHz Processor          1
Snapdragon 730G, Octa Core, 2.2 GHz Processor           1
Snapdragon  865, Octa Core, 2.84 GHz Processor          1
Exynos 9810, Octa Core, 2.7 GHz Processor               1
Exynos 9825, Octa Core, 2.7 GHz Processor               1
Exynos 7904, Octa Core, 1.8 GHz Processor               1
Helio P60, Octa Core, 1.99 GHz Processor                1
Exynos  9611 , Octa Core, 2.3 GHz Processor             1
Snapdragon  782G, Octa Core, 2.7 GHz Processor          1
Dimensity 8100 Ultra, Octa Core, 2.85 GHz Processor     1
Kirin 9000E, Octa Core, 3.13 GHz Processor              1
Helio A25, Octa Core, 1.8 GHz Processor                 1
Spreadtrum  SC7731, Quad Core, 1.3 GHz Processor        1
Snapdragon 662, Octa Core, 2 GHz Processor              1
Unisoc SC7731E, Quad Core, 1.3 GHz Processor            1
Snapdragon  712 , Octa Core, 2.3 GHz Processor          1
Snapdragon  730G, Octa Core, 2.2 GHz Processor          1
Helio  P22, Octa Core, 2 GHz Processor                  1
Dimensity 9200, Octa Core Processor                     1
Snapdragon 8 Gen1 , Octa Core, 3 GHz Processor          1
Google Tensor 3, Octa Core Processor                    1
Octa Core, 2.2 GHz Processor                            1
Tiger T610, Octa Core, 1.8 GHz Processor                1
Snapdragon  662 , Octa Core, 2 GHz Processor            1
Exynos 2100, Octa Core, 2.9 GHz Processor               1
Kirin 990, Octa Core, 2.86 GHz Processor                1
Snapdragon 675, Octa Core, 2 GHz Processor              1
Snapdragon 439, Octa Core, 1.95 GHz Processor           1
Exynos 9810, Octa Core, 2.8 GHz Processor               1
Exynos 1330, Octa Core Processor                        1
Snapdragon  778G+, Octa Core Processor                  1
Snapdragon 680 , Octa Core, 2.4 GHz Processor           1
Helio   G90T , Octa Core, 2.05 GHz Processor            1
(28 nm), Quad Core, 1.5 GHz Processor                   1
Kirin  810, Octa Core, 2.2 GHz Processor                1
Helio  P65 , Octa Core, 2 GHz Processor                 1
Helio P70, Octa Core, 2 GHz Processor                   1
Qualcomm Snapdragon 670, Octa Core, 2 GHz Processor     1
Samsung Exynos 7885, Octa Core, 2.2 GHz Processor       1
Kirin 659, Octa Core, 2.36 GHz Processor                1
Qualcomm Snapdragon 625, Octa Core, 2 GHz Processor     1
Snapdragon  7 Gen2, Octa Core Processor                 1
Snapdragon  7 Gen1, Octa Core, 2.4 GHz Processor        1
Helio  G88, Octa Core, 2 GHz Processor                  1
Snapdragon  690 , Octa Core, 2 GHz Processor            1
Spreadtrum  SC9832E , Quad Core, 1.4 GHz Processor      1
Dimensity 1000+, Octa Core, 2.6 GHz Processor           1
Snapdragon 665, Octa Core, 2 GHz Processor              1
Helio P35, Octa Core, 1.8 GHz Processor                 1
Snapdragon  855, Octa Core, 2.8 GHz Processor           1
Helio  G90T, Octa Core, 2.05 GHz Processor              1
Helio P70, Octa Core, 2.1 GHz Processor                 1
Helio P23, Octa Core, 2.5 GHz Processor                 1
Snapdragon MSM8939, Octa Core, 1.5 GHz Processor        1
Bionic A16, Hexa Core Processor                         1
Snapdragon 870 , Octa Core, 3.2 GHz Processor           1
Snapdragon 7 Gen1, Octa Core, 2.4 GHz Processor         1
Unisoc  A55, Octa Core, 1.6 GHz Processor               1
Snapdragon 450, Octa Core, 1.8 GHz Processor            1
Octa Core, 1.8 GHz Processor                            1
Snapdragon 710, Octa Core, 2.2 GHz Processor            1
Exynos 7885, Octa Core, 2.2 GHz Processor               1
Snapdragon 425, Quad Core, 1.2 GHz Processor            1
Spreadtrum  SC9832E, Quad Core, 1.4 GHz Processor       1
Google  Tensor 3, Octa Core Processor                   1
Name: count, dtype: int64

In [61]:
pd.set_option('display.max_rows', None)

In [62]:
df[~df['processor'].str.contains('Processor')]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
152,154,Apple iPhone 15 Pro Max,142990,79.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 256 GB inbuilt",4352 mAh Battery with 25W Fast Charging,"6.68 inches, 1284 x 2778 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15
263,265,Apple iPhone XR2,71999,60.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC",Apple A13,"4 GB RAM, 64 GB inbuilt",3060 mAh Battery with Fast Charging,"6.1 inches, 828 x 1792 px Display",12 MP + 5 MP Dual Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v12.3
282,284,Apple iPhone 14 Mini,69990,70.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC",Bionic A16,"6 GB RAM, 128 GB inbuilt",3500 mAh Battery with Fast Charging,"5.42 inches, 1080 x 2340 px Display with Punch...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v15
429,431,Nokia X50 5G,34999,76.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Snapdragon 775,"6 GB RAM, 64 GB inbuilt",6000 mAh Battery with 33W Fast Charging,"6.81 inches, 1080 x 2400 px Display with Punch...",108 MP Quad Rear & 32 MP Front Camera,Memory Card Supported,Android v11
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt",NaN,"6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15
627,629,Nokia 225 4G,3589,NaN,"Dual Sim, 3G, 4G, VoLTE",Unisoc T117,"64 MB RAM, 128 MB inbuilt",1150 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB",RTOS (Series 30+)
728,730,Apple iPhone 15,82990,72.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC",Bionic A16,"6 GB RAM, 128 GB inbuilt",3285 mAh Battery with Fast Charging,"6.06 inches, 1170 x 2532 px Display with Punch...",50 MP + 13 MP Dual Rear & 13 MP Front Camera,Memory Card Not Supported,iOS v15

In [64]:
df['sim'].value_counts()

sim
Dual Sim, 3G, 4G, VoLTE, Wi-Fi                               318
Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC                      268
Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi                           155
Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster                54
Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Blaster           52
Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC                           46
Dual Sim, 3G, 4G, VoLTE, Wi-Fi, IR Blaster                    46
Dual Sim, 3G, 4G, Wi-Fi                                        8
Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC                  7
Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC                      7
Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster                5
Single Sim, 3G, 4G, VoLTE, Wi-Fi, NFC                          4
Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi                       3
Single Sim, 3G, 4G, VoLTE, Wi-Fi                               3
Dual Sim, 3G, 4G, Wi-Fi, NFC                                   2
Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi                           1
Single Sim, 3G, 4G, Wi-Fi, NFC                                 1
Dual Sim, 3G, 4G, VoLTE                                        1
Dual Sim, 3G, Wi-Fi                                            1
Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster           1
Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC, IR Blaster      1
Name: count, dtype: int64

In [65]:
temp=df[~df['camera'].str.contains('MP')]
df.loc[temp.index,'camera']=df.loc[temp.index,'display']
df.loc[temp.index,'display']=df.loc[temp.index,'battery']
df.loc[temp.index,'battery']=np.nan

In [66]:
df.drop(884,inplace=True)

In [67]:
df.shape[0]/1020 # less than 4% rows are removed after the cleaning

0.9637254901960784

In [68]:
brand=df['model'].str.split(' ').str.get(0).str.lower()
df.insert(1,'brand',brand)

In [69]:
has5g=df['sim'].str.contains('5G')
nfc=df['sim'].str.contains('NFC')
has_ir_blaster=df['sim'].str.contains('IR Blaster')

In [70]:
df.insert(5,'has_5g',has5g)
df.insert(6,'nfc',nfc)
df.insert(7,'has_ir_blaster',has_ir_blaster)

In [ ]:
df.head()

In [71]:
processor_name = df['processor'].str.split(',').str.get(0)
num_core = df['processor'].str.split(',').str.get(1)
speed = df['processor'].str.split(',').str.get(2)

df.insert(10,'processor_name',processor_name)
df.insert(11,'num_core',num_core)
df.insert(12,'speed',speed)

In [73]:
df.head()

,index,brand,model,price,rating,has_5g,nfc,has_ir_blaster,sim,processor,processor_name,num_core,speed,ram,battery,display,camera,card,os
0,2,oneplus,OnePlus 11 5G,54999,89.0,True,True,False,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor",Snapdragon 8 Gen2,Octa Core,3.2 GHz Processor,"12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,3,oneplus,OnePlus Nord CE 2 Lite 5G,19989,81.0,True,False,False,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor",Snapdragon 695,Octa Core,2.2 GHz Processor,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,4,samsung,Samsung Galaxy A14 5G,16499,75.0,True,False,False,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor",Exynos 1330,Octa Core,2.4 GHz Processor,"4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,5,motorola,Motorola Moto G62 5G,14999,81.0,True,False,False,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor",Snapdragon 695,Octa Core,2.2 GHz Processor,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,6,realme,Realme 10 Pro Plus,24999,82.0,True,False,False,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor",Dimensity 1080,Octa Core,2.6 GHz Processor,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

In [72]:
df['processor_name']=df['processor_name'].str.strip()
temp=df[df['processor_name'].str.contains('Core')][['processor_name','num_core','speed']]
temp

           processor_name            num_core speed
118   Octa Core Processor                 NaN   NaN
143             Quad Core   1.4 GHz Processor   NaN
188             Quad Core   1.6 GHz Processor   NaN
201             Octa Core     2 GHz Processor   NaN
309             Octa Core     2 GHz Processor   NaN
315             Quad Core   1.3 GHz Processor   NaN
496   Octa Core Processor                 NaN   NaN
529   Octa Core Processor                 NaN   NaN
587             Octa Core     2 GHz Processor   NaN
758             Quad Core   1.6 GHz Processor   NaN
778             Octa Core   2.2 GHz Processor   NaN
794             Quad Core   1.3 GHz Processor   NaN
825   Octa Core Processor                 NaN   NaN
826   Octa Core Processor                 NaN   NaN
875   Octa Core Processor                 NaN   NaN
948   Octa Core Processor                 NaN   NaN
949   Octa Core Processor                 NaN   NaN
991             Octa Core   1.8 GHz Processor   NaN
1005            Quad Core   1.3 GHz Processor   NaN
1019  Octa Core Processor                 NaN   NaN

In [74]:
temp=temp.shift(1,axis=1)
temp

     processor_name             num_core               speed
118            None  Octa Core Processor                 NaN
143            None            Quad Core   1.4 GHz Processor
188            None            Quad Core   1.6 GHz Processor
201            None            Octa Core     2 GHz Processor
309            None            Octa Core     2 GHz Processor
315            None            Quad Core   1.3 GHz Processor
496            None  Octa Core Processor                 NaN
529            None  Octa Core Processor                 NaN
587            None            Octa Core     2 GHz Processor
758            None            Quad Core   1.6 GHz Processor
778            None            Octa Core   2.2 GHz Processor
794            None            Quad Core   1.3 GHz Processor
825            None  Octa Core Processor                 NaN
826            None  Octa Core Processor                 NaN
875            None  Octa Core Processor                 NaN
948            None  Octa Core Processor                 NaN
949            None  Octa Core Processor                 NaN
991            None            Octa Core   1.8 GHz Processor
1005           None            Quad Core   1.3 GHz Processor
1019           None  Octa Core Processor                 NaN

In [75]:
df.loc[temp.index,temp.columns]=temp

In [76]:
df['processor_name'].str.contains('Core').value_counts()

processor_name
False    963
Name: count, dtype: int64

In [77]:
df['processor_name'].str.contains('')

0       True
1       True
2       True
3       True
4       True
5       True
6       True
7       True
8       True
9       True
10      True
11      True
12      True
13      True
14      True
15      True
16      True
17      True
18      True
19      True
20      True
21      True
22      True
23      True
24      True
25      True
26      True
27      True
28      True
29      True
30      True
31      True
32      True
33      True
34      True
35      True
36      True
37      True
38      True
39      True
40      True
41      True
42      True
43      True
44      True
45      True
46      True
47      True
48      True
49      True
50      True
51      True
52      True
53      True
54      True
55      True
56      True
57      True
58      True
59      True
60      True
61      True
62      True
63      True
64      True
65      True
66      True
67      True
68      True
69      True
70      True
71      True
72      True
73      True
74      True
75      True
76      True
77      True
78      True
79      True
80      True
81      True
82      True
83      True
84      True
85      True
86      True
87      True
88      True
89      True
90      True
91      True
92      True
93      True
94      True
95      True
96      True
97      True
98      True
99      True
100     True
101     True
102     True
103     True
104     True
105     True
106     True
107     True
108     True
109     True
110     True
111     True
112     True
113     True
114     True
115     True
116     True
117     True
118     None
119     True
120     True
121     True
122     True
123     True
124     True
125     True
126     True
127     True
128     True
129     True
130     True
131     True
132     True
133     True
134     True
135     True
136     True
137     True
138     True
139     True
140     True
141     True
142     True
143     None
144     True
145     True
146     True
147     True
148     True
149     True
150     True
151     True
152     True
153     True
154     True
155     True
156     True
157     True
158     True
159     True
160     True
161     True
162     True
163     True
164     True
165     True
166     True
167     True
168     True
169     True
170     True
171     True
172     True
173     True
174     True
175     True
176     True
177     True
178     True
179     True
180     True
181     True
182     True
183     True
184     True
185     True
186     True
187     True
188     None
189     True
190     True
191     True
192     True
193     True
194     True
195     True
196     True
197     True
198     True
199     True
200     True
201     None
202     True
203     True
204     True
205     True
206     True
207     True
208     True
209     True
210     True
211     True
212     True
213     True
214     True
215     True
216     True
217     True
218     True
219     True
220     True
221     True
222     True
223     True
224     True
225     True
226     True
227     True
228     True
229     True
230     True
231     True
232     True
233     True
234     True
235     True
236     True
237     True
238     True
239     True
240     True
241     True
242     True
243     True
244     True
245     True
246     True
247     True
248     True
249     True
250     True
251     True
252     True
253     True
254     True
255     True
256     True
257     True
258     True
259     True
260     True
261     True
262     True
263     True
264     True
265     True
266     True
267     True
268     True
269     True
270     True
271     True
272     True
273     True
274     True
275     True
276     True
277     True
278     True
279     True
280     True
281     True
282     True
283     True
284     True
285     True
286     True
287     True
288     True
289     True
290     True
291     True
292     True
293     True
294     True
295     True
296     True
297     True
298     True
299     True
300     True
301     True
302     True
303     True
304     True
305     True
306     True
307     True
308     True
309     None
310     True
311     True
312     True
313     True
314     True
315     None
316     True
317     True
318     True
319     True
320     True
321     True
322     True
323     True
324     True
325     True
326     True
327     True
328     True
329     True
330     True
331     True
332     True
333     True
334     True
335     True
336     True
337     True
338     True
339     True
340     True
341     True
342     True
343     True
344     True
345     True
346     True
347     True
348     True
349     True
350     True
351     True
352     True
353     True
354     True
355     True
356     True
357     True
358     True
359     True
360     True
361     True
362     True
363     True
364     True
365     True
366     True
367     True
368     True
369     True
370     True
371     True
372     True
373     True
374     True
375     True
377     True
378     True
379     True
380     True
381     True
382     True
383     True
384     True
385     True
386     True
387     True
388     True
389     True
390     True
391     True
392     True
393     True
394     True
395     True
396     True
397     True
398     True
399     True
401     True
402     True
403     True
404     True
405     True
406     True
407     True
408     True
409     True
410     True
411     True
412     True
413     True
414     True
415     True
416     True
417     True
418     True
419     True
420     True
421     True
422     True
423     True
424     True
425     True
426     True
427     True
428     True
429     True
430     True
431     True
432     True
433     True
434     True
435     True
436     True
437     True
438     True
439     True
440     True
441     True
442     True
443     True
444     True
445     True
446     True
447     True
448     True
449     True
450     True
451     True
452     True
453     True
454     True
455     True
456     True
457     True
458     True
459     True
460     True
461     True
462     True
463     True
464     True
465     True
466     True
467     True
468     True
469     True
470     True
471     True
472     True
474     True
475     True
476     True
477     True
478     True
479     True
480     True
481     True
482     True
483     True
484     True
485     True
486     True
487     True
488     True
489     True
490     True
491     True
492     True
493     True
494     True
495     True
496     None
497     True
498     True
499     True
500     True
501     True
502     True
503     True
504     True
505     True
506     True
507     True
508     True
509     True
510     True
511     True
512     True
513     True
514     True
515     True
516     True
517     True
518     True
519     True
520     True
521     True
522     True
523     True
524     True
525     True
526     True
527     True
528     True
529     None
530     True
531     True
534     True
535     True
536     True
537     True
538     True
539     True
540     True
541     True
542     True
543     True
544     True
545     True
546     True
547     True
548     True
549     True
550     True
552     True
553     True
554     True
555     True
556     True
557     True
558     True
559     True
560     True
561     True
562     True
563     True
564     True
565     True
566     True
567     True
568     True
569     True
570     True
571     True
572     True
574     True
576     True
577     True
578     True
579     True
580     True
581     True
583     True
584     True
585     True
586     True
587     None
588     True
589     True
590     True
591     True
592     True
593     True
594     True
595     True
596     True
597     True
598     True
599     True
600     True
601     True
602     True
603     True
604     True
605     True
606     True
607     True
609     True
610     True
612     True
613     True
614     True
615     True
616     True
617     True
618     True
619     True
620     True
621     True
622     True
623     True
624     True
625     True
626     True
627     True
628     True
629     True
630     True
631     True
632     True
633     True
634     True
635     True
636     True
637     True
638     True
639     True
641     True
642     True
643     True
644     True
646     True
648     True
649     True
650     True
651     True
652     True
653     True
654     True
655     True
656     True
658     True
659     True
660     True
661     True
662     True
663     True
664     True
666     True
667     True
668     True
669     True
670     True
671     True
672     True
673     True
674     True
675     True
676     True
677     True
678     True
679     True
680     True
681     True
682     True
683     True
684     True
686     True
687     True
688     True
689     True
690     True
691     True
692     True
693     True
694     True
695     True
696     True
697     True
698     True
700     True
701     True
702     True
703     True
704     True
705     True
706     True
707     True
708     True
709     True
710     True
711     True
712     True
713     True
714     True
715     True
716     True
717     True
718     True
719     True
720     True
721     True
722     True
723     True
724     True
725     True
726     True
727     True
728     True
729     True
730     True
731     True
732     True
733     True
734     True
735     True
736     True
737     True
738     True
739     True
740     True
741     True
742     True
743     True
744     True
745     True
746     True
747     True
749     True
750     True
751     True
752     True
753     True
755     True
756     True
758     None
759     True
760     True
761     True
762     True
763     True
764     True
765     True
766     True
767     True
768     True
769     True
770     True
771     True
772     True
773     True
774     True
775     True
776     True
777     True
778     None
779     True
780     True
781     True
782     True
783     True
784     True
785     True
786     True
787     True
788     True
789     True
790     True
791     True
792     True
793     True
794     None
795     True
796     True
797     True
798     True
799     True
800     True
801     True
802     True
803     True
804     True
805     True
806     True
807     True
808     True
809     True
810     True
811     True
812     True
813     True
814     True
815     True
816     True
818     True
819     True
820     True
821     True
822     True
823     True
824     True
825     None
826     None
827     True
828     True
829     True
830     True
831     True
832     True
833     True
834     True
836     True
837     True
838     True
839     True
840     True
841     True
842     True
843     True
844     True
845     True
847     True
848     True
849     True
850     True
851     True
853     True
854     True
855     True
856     True
858     True
859     True
860     True
861     True
862     True
863     True
864     True
865     True
866     True
867     True
868     True
869     True
870     True
871     True
872     True
874     True
875     None
876     True
877     True
878     True
879     True
880     True
883     True
885     True
886     True
887     True
888     True
889     True
890     True
891     True
892     True
893     True
894     True
895     True
896     True
897     True
898     True
899     True
900     True
901     True
902     True
903     True
904     True
905     True
906     True
907     True
908     True
909     True
910     True
911     True
912     True
913     True
914     True
915     True
916     True
918     True
919     True
920     True
921     True
922     True
923     True
924     True
926     True
928     True
929     True
931     True
933     True
934     True
935     True
936     True
937     True
938     True
939     True
940     True
941     True
942     True
943     True
944     True
945     True
946     True
947     True
948     None
949     None
950     True
951     True
952     True
953     True
954     True
955     True
956     True
957     True
958     True
959     True
960     True
961     True
962     True
963     True
964     True
965     True
966     True
967     True
968     True
969     True
970     True
971     True
972     True
973     True
974     True
975     True
976     True
977     True
978     True
979     True
980     True
981     True
982     True
983     True
984     True
985     True
986     True
987     True
989     True
990     True
991     None
992     True
993     True
994     True
995     True
996     True
997     True
998     True
999     True
1001    True
1002    True
1003    True
1004    True
1005    None
1006    True
1007    True
1008    True
1009    True
1010    True
1011    True
1012    True
1013    True
1014    True
1015    True
1016    True
1017    True
1018    True
1019    None
Name: processor_name, dtype: object

In [78]:
df.loc[856,'processor_name']='Mediatek'

In [79]:
b=df['processor_name'].str.split(" ").str.get(0)
df.insert(10,'processor_brand',b)

In [80]:
df.head()

,index,brand,model,price,rating,has_5g,nfc,has_ir_blaster,sim,processor,processor_brand,processor_name,num_core,speed,ram,battery,display,camera,card,os
0,2,oneplus,OnePlus 11 5G,54999,89.0,True,True,False,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor",Snapdragon,Snapdragon 8 Gen2,Octa Core,3.2 GHz Processor,"12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,3,oneplus,OnePlus Nord CE 2 Lite 5G,19989,81.0,True,False,False,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor",Snapdragon,Snapdragon 695,Octa Core,2.2 GHz Processor,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,4,samsung,Samsung Galaxy A14 5G,16499,75.0,True,False,False,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor",Exynos,Exynos 1330,Octa Core,2.4 GHz Processor,"4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,5,motorola,Motorola Moto G62 5G,14999,81.0,True,False,False,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor",Snapdragon,Snapdragon 695,Octa Core,2.2 GHz Processor,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,6,realme,Realme 10 Pro Plus,24999,82.0,True,False,False,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor",Dimensity,Dimensity 1080,Octa Core,2.6 GHz Processor,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

In [82]:
df['num_core']=df['num_core'].str.strip()

In [86]:
df['num_core'].value_counts()

num_core
Octa Core              870
Quad Core               38
Hexa Core               31
Octa Core Processor     28
Hexa Core Processor      8
Dual Core                1
Name: count, dtype: int64

In [88]:
df['num_core']=df['num_core'].str.replace('Octa Core Processor','Octa Core')
df['num_core']=df['num_core'].str.replace('Hexa Core Processor','Hexa Core')

In [89]:
df['num_core'].value_counts()

num_core
Octa Core    898
Hexa Core     39
Quad Core     38
Dual Core      1
Name: count, dtype: int64

In [90]:
df['speed'].value_counts()

speed
2 GHz Processor       146
2.2 GHz Processor     135
2.4 GHz Processor     127
3.2 GHz Processor      94
2.3 GHz Processor      86
3 GHz Processor        53
2.84 GHz Processor     36
2.05 GHz Processor     28
2.5 GHz Processor      23
1.8 GHz Processor      23
1.6 GHz Processor      20
2.85 GHz Processor     19
3.22 GHz Processor     18
3.1 GHz Processor      15
2.6 GHz Processor      14
2.9 GHz Processor      13
1.3 GHz Processor      11
1.82 GHz Processor     10
2.8 GHz Processor       9
2.73 GHz Processor      9
2.36 GHz Processor      8
3.05 GHz Processor      8
2.65 GHz Processor      5
1.4 GHz Processor       5
2.7 GHz Processor       5
1.5 GHz Processor       4
2.96 GHz Processor      3
2.86 GHz Processor      3
1.1 GHz Processor       2
3.13 GHz Processor      2
2.35 GHz Processor      1
2.37 GHz Processor      1
1.99 GHz Processor      1
1.95 GHz Processor      1
2.1 GHz Processor       1
1.2 GHz Processor       1
Name: count, dtype: int64

In [93]:
df['speed'] = (
    df['speed']
    .str.strip()
    .str.replace('\u2009', ' ', regex=False)
)

In [97]:
xn=df['speed'].str.split(' ').str.get(0)
df['speed']=xn

In [102]:
df['speed']=df['speed'].astype('float')

In [104]:
df.info()

<class 'pandas.DataFrame'>
Index: 983 entries, 0 to 1019
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   index            983 non-null    int64
 1   brand            983 non-null    object
 2   model            983 non-null    str
 3   price            983 non-null    int64
 4   rating           878 non-null    float64
 5   has_5g           983 non-null    bool
 6   nfc              983 non-null    bool
 7   has_ir_blaster   983 non-null    bool
 8   sim              983 non-null    str
 9   processor        983 non-null    str
 10  processor_brand  963 non-null    object
 11  processor_name   963 non-null    object
 12  num_core         976 non-null    object
 13  speed            940 non-null    float64
 14  ram              983 non-null    str
 15  battery          971 non-null    str
 16  display          983 non-null    str
 17  camera           983 non-null    str
 18  card             983 non-null    str
 19  os               965 non-null    str
dtypes: bool(3), float64(2), int64(2), object(4), str(9)
memory usage: 173.4+ KB

In [117]:
num=df['ram'].str.split(',').str.get(0).str.split('\u2009').str.get(0)
df.insert(14,'ram_capacity',num)

In [118]:
df.head(1)

,index,brand,model,price,rating,has_5g,nfc,has_ir_blaster,sim,processor,...,processor_name,num_core,speed,ram_capacity,ram,battery,display,camera,card,os
0,2,oneplus,OnePlus 11 5G,54999,89.0,True,True,False,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor",...,Snapdragon 8 Gen2,Octa Core,3.2,12,"12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13

In [ ]:
num=df['ram'].str.split(',').str.get(1).str.split('\u2009').str.get(0)
df.insert(14,'inbuilt',num)

In [120]:
df.head(1)

,index,brand,model,price,rating,has_5g,nfc,has_ir_blaster,sim,processor,...,num_core,speed,inbuilt,ram_capacity,ram,battery,display,camera,card,os
0,2,oneplus,OnePlus 11 5G,54999,89.0,True,True,False,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor",...,Octa Core,3.2,256,12,"12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13

In [125]:
df.info()

<class 'pandas.DataFrame'>
Index: 983 entries, 0 to 1019
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   index            983 non-null    int64
 1   brand            983 non-null    object
 2   model            983 non-null    str
 3   price            983 non-null    int64
 4   rating           878 non-null    float64
 5   has_5g           983 non-null    bool
 6   nfc              983 non-null    bool
 7   has_ir_blaster   983 non-null    bool
 8   sim              983 non-null    str
 9   processor        983 non-null    str
 10  processor_brand  963 non-null    object
 11  processor_name   963 non-null    object
 12  num_core         976 non-null    object
 13  speed            940 non-null    float64
 14  inbuilt          980 non-null    float64
 15  ram_capacity     983 non-null    float64
 16  ram              983 non-null    str
 17  battery          971 non-null    str
 18  display          983 non-null    str
 19  camera           983 non-null    str
 20  card             983 non-null    str
 21  os               965 non-null    str
dtypes: bool(3), float64(4), int64(2), object(4), str(9)
memory usage: 188.8+ KB

In [124]:
df['inbuilt']=df['inbuilt'].astype('float')
df['ram_capacity']=df['ram_capacity'].astype('float')

In [133]:
df[df['ram_capacity']>18]

,index,brand,model,price,rating,has_5g,nfc,has_ir_blaster,sim,processor,...,num_core,speed,inbuilt,ram_capacity,ram,battery,display,camera,card,os
271,273,nokia,Nokia 2720 V Flip,6199,NaN,False,False,False,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 205 , Dual Core, 1.1 GHz Processor",...,Dual Core,1.1,4.0,512.0,"512 MB RAM, 4 GB inbuilt",1500 mAh Battery,"2.8 inches, 240 x 320 px Display",2 MP Rear Camera,Memory Card Supported,NaN
483,485,huawei,Huawei Mate 50 RS Porsche Design,239999,81.0,False,True,True,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor",...,Octa Core,3.2,NaN,512.0,512 GB inbuilt,4700 mAh Battery with 66W Fast Charging,"6.74 inches, 1212 x 2616 px, 120 Hz Display",50 MP + 48 MP + 13 MP Triple Rear & 13 MP Fron...,"Memory Card (Hybrid), upto 256 GB",Hongmeng OS v3.0
486,488,nokia,Nokia 8000 4G,6899,NaN,False,False,False,"Dual Sim, 3G, 4G, Wi-Fi","Snapdragon 210, Quad Core, 1.1 GHz Processor",...,Quad Core,1.1,4.0,512.0,"512 MB RAM, 4 GB inbuilt",1500 mAh Battery,"2.8 inches, 240 x 320 px Display",2 MP Rear Camera,Memory Card Supported,NaN
627,629,nokia,Nokia 225 4G,3589,NaN,False,False,False,"Dual Sim, 3G, 4G, VoLTE",Unisoc T117,...,NaN,NaN,128.0,64.0,"64 MB RAM, 128 MB inbuilt",1150 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB",RTOS (Series 30+)

In [131]:
df.loc[[439,762],['ram_capacity','inbuilt']]=[[4,64],[4,64]]

In [132]:
df.loc[[439,762],['ram_capacity','inbuilt']]

     ram_capacity  inbuilt
439           4.0     64.0
762           4.0     64.0

In [134]:
df.loc[[483],['ram_capacity','inbuilt']]=[12,4]

In [135]:
df.drop([627,486],inplace=True)

In [138]:
df['ram_capacity'].value_counts()

ram_capacity
8.0     338
6.0     234
4.0     218
12.0     86
3.0      54
2.0      32
16.0      9
1.0       7
18.0      2
Name: count, dtype: int64

In [137]:
df.drop([271],inplace=True)

In [145]:
temp=df[df['inbuilt']==1]

In [143]:
df.loc[temp.index,'inbuilt']=1024

In [156]:
b=df['battery'].str.split('with').str.get(0).str.split().str.get(0)
df.insert(15,'battery_capacity',b)

In [161]:
df.head(4)

,index,brand,model,price,rating,has_5g,nfc,has_ir_blaster,sim,processor,...,speed,inbuilt,battery_capacity,ram_capacity,ram,battery,display,camera,card,os
0,2,oneplus,OnePlus 11 5G,54999,89.0,True,True,False,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor",...,3.2,256.0,5000,12.0,"12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,3,oneplus,OnePlus Nord CE 2 Lite 5G,19989,81.0,True,False,False,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor",...,2.2,128.0,5000,6.0,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,4,samsung,Samsung Galaxy A14 5G,16499,75.0,True,False,False,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor",...,2.4,64.0,5000,4.0,"4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,5,motorola,Motorola Moto G62 5G,14999,81.0,True,False,False,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor",...,2.2,128.0,5000,6.0,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12

In [167]:
b=df['battery'].str.split('with').str.get(1).str.split().str.get(0)
b=b.str.replace('W', '')
df['fast_charging']=b

In [174]:
df['fast_charging'].isna().sum()

np.int64(145)

In [178]:
def convert(x):
    if pd.isna(x):
        return -1
    elif x == 'Fast':
        return 0
    else:
        return x
df['fast_charging'] = df['fast_charging'].apply(convert)

In [179]:
df['fast_charging'].value_counts()

fast_charging
33      152
-1      145
18      128
0        68
67       65
25       53
120      46
15       43
80       42
66       35
10       33
30       32
65       30
44       23
45       17
20       10
100       7
150       7
68        7
125       6
40        5
22.5      5
60        4
55        3
210       2
50        2
21        2
180       1
200       1
240       1
19        1
135       1
165       1
27        1
68.2      1
Name: count, dtype: int64

In [185]:
df['fast_charging'].astype('float')

0       100.0
1        33.0
2        15.0
3         0.0
4        67.0
5        25.0
6         0.0
7       120.0
8        33.0
9        80.0
10       33.0
11       33.0
12       67.0
13       18.0
14       45.0
15        0.0
16       10.0
17       80.0
18       80.0
19       18.0
20      100.0
21       66.0
22       67.0
23       33.0
24      100.0
25        0.0
26       33.0
27        0.0
28       44.0
29      100.0
30       33.0
31       67.0
32       67.0
33       -1.0
34       25.0
35       25.0
36       66.0
37       45.0
38      210.0
39       67.0
40       67.0
41       67.0
42       30.0
43       67.0
44       44.0
45       25.0
46       33.0
47       -1.0
48       10.0
49       33.0
50       15.0
51      120.0
52       18.0
53       30.0
54       33.0
55       18.0
56        0.0
57       33.0
58       45.0
59       33.0
60       67.0
61       66.0
62       25.0
63       18.0
64       33.0
65       66.0
66       80.0
67      120.0
68       25.0
69       67.0
70       -1.0
71       44.0
72       18.0
73      150.0
74       18.0
75       -1.0
76        0.0
77       67.0
78       33.0
79       -1.0
80       33.0
81       15.0
82       18.0
83       18.0
84       15.0
85       33.0
86       25.0
87       33.0
88       33.0
89       25.0
90       18.0
91        0.0
92        0.0
93       80.0
94       -1.0
95       33.0
96        0.0
97      120.0
98       66.0
99       18.0
100       0.0
101      33.0
102      68.0
103      33.0
104      50.0
105     120.0
106     120.0
107      25.0
108      44.0
109      80.0
110      45.0
111      -1.0
112      67.0
113      25.0
114      10.0
115      80.0
116      25.0
117      66.0
118     120.0
119      25.0
120      68.0
121      80.0
122       0.0
123      33.0
124      25.0
125      44.0
126      20.0
127      33.0
128      25.0
129       0.0
130      18.0
131      18.0
132      -1.0
133      33.0
134      67.0
135      67.0
136      -1.0
137      18.0
138      33.0
139      80.0
140      18.0
141      67.0
142      33.0
143      -1.0
144      18.0
145      15.0
146      66.0
147      25.0
148      18.0
149      -1.0
150      33.0
151      33.0
152      25.0
153      67.0
154      33.0
155      -1.0
156      -1.0
157      33.0
158      65.0
159      67.0
160      33.0
161      33.0
162       0.0
163      80.0
164     120.0
165      15.0
166      33.0
167      33.0
168      66.0
169      18.0
170      -1.0
171      67.0
172      33.0
173      18.0
174       0.0
175      18.0
176      33.0
177      33.0
178      18.0
179      44.0
180      33.0
181     180.0
182      10.0
183     125.0
184      25.0
185      33.0
186     120.0
187      30.0
188      -1.0
189      10.0
190      -1.0
191      -1.0
192      25.0
193      65.0
194      68.0
195      18.0
196      80.0
197      33.0
198      67.0
199      15.0
200      33.0
201      25.0
202     125.0
203     120.0
204      33.0
205      18.0
206      33.0
207      25.0
208      18.0
209      67.0
210       0.0
211      66.0
212      18.0
213      33.0
214      -1.0
215      40.0
216      30.0
217      33.0
218      44.0
219      -1.0
220      67.0
221      60.0
222      18.0
223      33.0
224      33.0
225      10.0
226      -1.0
227      33.0
228      80.0
229      80.0
230      80.0
231     200.0
232      18.0
233      18.0
234      33.0
235      44.0
236      67.0
237      10.0
238      33.0
239      44.0
240     120.0
241      33.0
242      67.0
243      66.0
244      30.0
245      33.0
246      33.0
247       0.0
248      30.0
249      80.0
250      20.0
251      45.0
252      45.0
253      18.0
254      67.0
255      67.0
256      33.0
257      45.0
258      18.0
259      30.0
260      18.0
261      18.0
262      -1.0
263       0.0
264      25.0
265      33.0
266      65.0
267     100.0
268      67.0
269      66.0
270      15.0
272      30.0
273      33.0
274      18.0
275      67.0
276     120.0
277       0.0
278      33.0
279      -1.0
280      65.0
281      44.0
282       0.0
283      18.0
284     120.0
285      25.0
286      67.0
287      67.0
288      33.0
289      18.0
290       0.0
291      15.0
292      33.0
293      33.0
294      -1.0
295      25.0
296     125.0
297      33.0
298      67.0
299      -1.0
300      10.0
301      67.0
302      -1.0
303      -1.0
304      18.0
305      33.0
306      15.0
307      -1.0
308     150.0
309      25.0
310      65.0
311       0.0
312      25.0
313      45.0
314      33.0
315      -1.0
316      66.0
317      15.0
318      80.0
319      66.0
320     120.0
321      25.0
322      -1.0
323       0.0
324      25.0
325      -1.0
326      30.0
327      33.0
328      25.0
329      18.0
330      18.0
331      33.0
332      66.0
333      25.0
334      30.0
335      67.0
336      33.0
337      -1.0
338      20.0
339      65.0
340      33.0
341      -1.0
342      33.0
343       0.0
344      33.0
345      33.0
346       0.0
347     120.0
348     120.0
349      10.0
350      20.0
351      10.0
352      -1.0
353      -1.0
354     120.0
355      10.0
356      18.0
357      33.0
358      -1.0
359      67.0
360      33.0
361     120.0
362     120.0
363      -1.0
364      45.0
365      44.0
366     150.0
367      -1.0
368      25.0
369      33.0
370      30.0
371      33.0
372      33.0
373      25.0
374       0.0
375      15.0
377      66.0
378      33.0
379      65.0
380      25.0
381      25.0
382      10.0
383      -1.0
384      -1.0
385      18.0
386      66.0
387      60.0
388      15.0
389      33.0
390      18.0
391      33.0
392      44.0
393      15.0
394      33.0
395      33.0
396      18.0
397      15.0
398      33.0
399      -1.0
401     240.0
402       0.0
403      10.0
404      67.0
405      33.0
406      33.0
407      80.0
408      65.0
409      67.0
410     120.0
411      33.0
412      30.0
413      15.0
414      18.0
415      33.0
416      65.0
417      65.0
418      -1.0
419      67.0
420       0.0
421      33.0
422     125.0
423      67.0
424      66.0
425      80.0
426      44.0
427      18.0
428     120.0
429      33.0
430      33.0
431      -1.0
432      15.0
433      33.0
434      67.0
435       0.0
436      -1.0
437      10.0
438      33.0
439      -1.0
440      25.0
441      33.0
442      -1.0
443      15.0
444      10.0
445      65.0
446     120.0
447      -1.0
448      -1.0
449      18.0
450      18.0
451      80.0
452      19.0
453      33.0
454      15.0
455      -1.0
456      30.0
457       0.0
458      66.0
459      33.0
460      18.0
461      -1.0
462      40.0
463     120.0
464      80.0
465      15.0
466      10.0
467      18.0
468      80.0
469      33.0
470      33.0
471      -1.0
472      45.0
474      15.0
475      25.0
476       0.0
477      -1.0
478      -1.0
479      10.0
480      -1.0
481      -1.0
482      80.0
483      66.0
484      33.0
485      44.0
487      21.0
488       0.0
489      30.0
490      45.0
491      66.0
492      18.0
493     135.0
494      18.0
495      80.0
496       0.0
497      67.0
498      33.0
499      80.0
500      66.0
501      18.0
502      -1.0
503      20.0
504      25.0
505      -1.0
506       0.0
507      10.0
508      66.0
509      33.0
510      -1.0
511      15.0
512      15.0
513      60.0
514      18.0
515      18.0
516     150.0
517     210.0
518      15.0
519      80.0
520       0.0
521      44.0
522      33.0
523      60.0
524      -1.0
525      33.0
526      65.0
527       0.0
528      33.0
529      25.0
530      33.0
531      18.0
534      80.0
535      30.0
536      10.0
537      18.0
538      18.0
539      18.0
540      65.0
541     120.0
542      33.0
543      66.0
544      25.0
545      68.0
546      18.0
547      18.0
548      33.0
549      33.0
550      44.0
552      33.0
553      33.0
554      66.0
555      30.0
556      25.0
557      67.0
558      18.0
559      80.0
560      65.0
561      67.0
562      -1.0
563      33.0
564      18.0
565      65.0
566      65.0
567      15.0
568     165.0
569      25.0
570       0.0
571      33.0
572      25.0
574      -1.0
576      -1.0
577      -1.0
578      66.0
579     120.0
580      20.0
581      33.0
583     125.0
584      67.0
585      66.0
586      18.0
587      25.0
588      -1.0
589      18.0
590      18.0
591      80.0
592     120.0
593      80.0
594     120.0
595      -1.0
596      -1.0
597      -1.0
598      18.0
599      18.0
600      18.0
601      15.0
602      33.0
603      65.0
604      30.0
605      45.0
606      18.0
607      -1.0
609      33.0
610      -1.0
612      33.0
613      66.0
614      80.0
615      67.0
616      67.0
617      33.0
618      44.0
619      33.0
620      30.0
621      18.0
622      18.0
623      18.0
624      -1.0
625      -1.0
626      33.0
628      -1.0
629      21.0
630      18.0
631      25.0
632      15.0
633      67.0
634      80.0
635      10.0
636       0.0
637     120.0
638      33.0
639      33.0
641      45.0
642     120.0
643     120.0
644      -1.0
646      25.0
648      18.0
649      66.0
650      -1.0
651      65.0
652      50.0
653      18.0
654      -1.0
655      -1.0
656      18.0
658      10.0
659     120.0
660      44.0
661      33.0
662      44.0
663      18.0
664      33.0
666      18.0
667      33.0
668      18.0
669     120.0
670      18.0
671      -1.0
672      18.0
673      15.0
674      18.0
675      67.0
676      33.0
677      33.0
678      33.0
679      33.0
680      25.0
681      18.0
682       0.0
683      25.0
684       0.0
686     120.0
687      15.0
688      15.0
689      10.0
690      18.0
691      18.0
692     120.0
693      33.0
694      15.0
695     120.0
696      -1.0
697      -1.0
698      30.0
700      80.0
701      18.0
702      67.0
703      33.0
704       0.0
705      18.0
706      33.0
707      15.0
708      30.0
709      45.0
710      30.0
711      -1.0
712      18.0
713      30.0
714      20.0
715      15.0
716      45.0
717      -1.0
718      18.0
719      80.0
720      33.0
721      65.0
722      68.0
723     120.0
724      66.0
725      -1.0
726      66.0
727      67.0
728       0.0
729      33.0
730      -1.0
731      -1.0
732     120.0
733      18.0
734      -1.0
735      -1.0
736      66.0
737      67.0
738      -1.0
739      30.0
740      65.0
741      20.0
742      65.0
743      18.0
744      -1.0
745      33.0
746      33.0
747      33.0
749      25.0
750      18.0
751      30.0
752      20.0
753      -1.0
755       0.0
756      10.0
758      -1.0
759      67.0
760     120.0
761     100.0
762      -1.0
763      18.0
764       0.0
765      67.0
766      44.0
767      33.0
768      67.0
769      80.0
770      65.0
771      -1.0
772      22.5
773      15.0
774      45.0
775      18.0
776      67.0
777      80.0
778      -1.0
779      18.0
780      -1.0
781       0.0
782      -1.0
783      44.0
784      -1.0
785      67.0
786      -1.0
787      15.0
788       0.0
789      18.0
790      67.0
791      18.0
792       0.0
793      -1.0
794      -1.0
795      18.0
796      25.0
797      33.0
798      25.0
799      30.0
800      40.0
801      -1.0
802       0.0
803      -1.0
804      -1.0
805       0.0
806     120.0
807      15.0
808       0.0
809       0.0
810     120.0
811      18.0
812      80.0
813       0.0
814       0.0
815      18.0
816      18.0
818      -1.0
819      33.0
820      18.0
821      10.0
822     120.0
823      33.0
824      33.0
825       0.0
826       0.0
827      80.0
828       0.0
829      33.0
830      -1.0
831      67.0
832      18.0
833      67.0
834      18.0
836      18.0
837      18.0
838      -1.0
839      18.0
840       0.0
841      -1.0
842      65.0
843      67.0
844      -1.0
845      33.0
847      18.0
848      33.0
849     120.0
850       0.0
851      18.0
853      -1.0
854      10.0
855      30.0
856      -1.0
858      65.0
859      -1.0
860      18.0
861      -1.0
862      40.0
863      18.0
864      18.0
865      22.5
866      18.0
867      10.0
868      18.0
869      15.0
870      25.0
871      -1.0
872      -1.0
874      33.0
875      22.5
876      45.0
877      80.0
878      18.0
879      33.0
880      -1.0
883      -1.0
885      40.0
886       0.0
887     120.0
888      80.0
889      18.0
890     150.0
891     120.0
892      33.0
893      33.0
894      -1.0
895      18.0
896      44.0
897      -1.0
898      65.0
899      30.0
900      -1.0
901      18.0
902      67.0
903      20.0
904      65.0
905      30.0
906      30.0
907      -1.0
908      25.0
909      65.0
910      65.0
911      15.0
912      18.0
913      -1.0
914      -1.0
915      -1.0
916      18.0
918      -1.0
919      65.0
920      25.0
921      27.0
922      18.0
923      -1.0
924      -1.0
926      -1.0
928       0.0
929      18.0
931      -1.0
933      33.0
934      80.0
935      10.0
936      10.0
937      -1.0
938      -1.0
939      55.0
940      10.0
941      67.0
942      10.0
943      25.0
944      33.0
945     125.0
946     150.0
947     100.0
948       0.0
949      18.0
950      33.0
951     150.0
952      18.0
953      44.0
954      66.0
955      80.0
956      -1.0
957      55.0
958      33.0
959     120.0
960      15.0
961       0.0
962      30.0
963      -1.0
964      33.0
965      -1.0
966      18.0
967      67.0
968      66.0
969       0.0
970      18.0
971      66.0
972      -1.0
973      15.0
974      65.0
975      18.0
976      15.0
977      15.0
978      -1.0
979      -1.0
980      33.0
981      18.0
982      18.0
983      -1.0
984      -1.0
985      30.0
986      -1.0
987      30.0
989       0.0
990       0.0
991      15.0
992      -1.0
993      55.0
994       0.0
995      -1.0
996      -1.0
997      -1.0
998      10.0
999      22.5
1001     10.0
1002     33.0
1003     -1.0
1004     68.0
1005     -1.0
1006     -1.0
1007     67.0
1008     68.0
1009     80.0
1010     10.0
1011    120.0
1012     -1.0
1013     67.0
1014     66.0
1015     68.2
1016     22.5
1017     67.0
1018      0.0
1019      0.0
Name: fast_charging, dtype: float64

In [198]:
xm=df['display'].str.strip().str.split(',').str.get(0).str.strip().str.split(' ').str.get(0)
df.insert(20,'screen_size',xm)

In [199]:
df.head()

,index,brand,model,price,rating,has_5g,nfc,has_ir_blaster,sim,processor,...,battery_capacity,fast_charging,ram_capacity,ram,battery,screen_size,display,camera,card,os
0,2,oneplus,OnePlus 11 5G,54999,89.0,True,True,False,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor",...,5000,100,12.0,"12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,6.7,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,3,oneplus,OnePlus Nord CE 2 Lite 5G,19989,81.0,True,False,False,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor",...,5000,33,6.0,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,6.59,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,4,samsung,Samsung Galaxy A14 5G,16499,75.0,True,False,False,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor",...,5000,15,4.0,"4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,6.6,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,5,motorola,Motorola Moto G62 5G,14999,81.0,True,False,False,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor",...,5000,0,6.0,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,6.55,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,6,realme,Realme 10 Pro Plus,24999,82.0,True,False,False,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor",...,5000,67,6.0,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,6.7,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

In [201]:
df['screen_size'] = (
    df['screen_size']
    .str.replace('\u2009mAh', '', regex=False)
    .astype(float)
)

In [209]:
resolution= df['display'].str.strip().str.split(' ').str.get(2).str.split('px').str.get(0)
df.insert(21,'resolution',resolution)

In [210]:
df.head(2)

,index,brand,model,price,rating,has_5g,nfc,has_ir_blaster,sim,processor,...,fast_charging,ram_capacity,ram,battery,screen_size,resolution,display,camera,card,os
0,2,oneplus,OnePlus 11 5G,54999,89.0,True,True,False,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor",...,100,12.0,"12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,6.70,1440 x 3216,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,3,oneplus,OnePlus Nord CE 2 Lite 5G,19989,81.0,True,False,False,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor",...,33,6.0,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,6.59,1080 x 2412,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12

In [217]:
r=df['display'].str.strip().str.split(',').str.get(2).str.split(' ').str.get(1)
df.insert(22,'refreshrate',r)

In [219]:
def func(item):
    if pd.isna(item):
        return '60'
    else:
        return item

df['refreshrate']=df['refreshrate'].apply(func)

In [ ]:
df['refreshrate'].value_counts()

refreshrate
60     370
120    342
90     219
144     39
165      9
240      1
Name: count, dtype: int64

In [221]:
df['refreshrate']=df['refreshrate'].astype('int')

In [233]:
def func(text):
    if 'Triple' in text:
        return 3
    elif 'Quad' in text:
        return 4
    elif 'Dual' in text:
        return 2
    else:
       return 1

nm = df['camera'].str.split('&').str.get(0).apply(func)

In [234]:
df['rear_cam']=nm

In [239]:
def func(text):
    if pd.isna(text):
        return 0
    elif 'Dual' in text:
        return 2
    else:
        return 1

nm=df['camera'].str.split('&').str.get(1).apply(func)

In [241]:
df.insert(23,'front_cam',nm)

In [242]:
df['front_cam'].value_counts()

front_cam
1    946
2     29
0      5
Name: count, dtype: int64

In [243]:
df['front_cam']=df['front_cam'].astype('int')